// export default {
//   upper: [
//     {
//       id: 20512,
//       name: 'UB Semi Final',
//       nextMatchId: 20515,
//       nextLooserMatchId: 20502,
//       tournamentRoundText: 'UB 3',
//       startTime: 'August 05, 2021',
//       state: 'SCORE_DONE',
//       participants: [
//         {
//           id: 'a3c107d2-ded2-4f33-85e7-2215805f664b',
//           resultText: '0',
//           isWinner: false,
//           status: 'PLAYED',
//           name: 'BTC',
//         },
//         {
//           id: 'a3fb4b05-d4ee-4efe-84cf-b500cdbdbbe0',
//           resultText: '2',
//           isWinner: true,
//           status: 'PLAYED',
//           name: 'Towby',
//         },
//       ],
//     },
//     {
//       id: 20513,
//       name: 'UB 2.1',
//       nextMatchId: 20512,
//       nextLooserMatchId: 20506,
//       tournamentRoundText: 'UB 2',
//       startTime: 'August 05, 2021',
//       state: 'SCORE_DONE',
//       participants: [
//         {
//           id: '8cf422cd-a99d-4184-b2cd-70ee481f46b3',
//           resultText: '0',
//           isWinner: false,
//           status: 'PLAYED',
//           name: 'GlootOne',
//         },
//         {
//           id: 'a3fb4b05-d4ee-4efe-84cf-b500cdbdbbe0',
//           resultText: '2',
//           isWinner: true,
//           status: 'PLAYED',
//           name: 'Towby',
//         },
//       ],
//     },
//     {
//       id: 20514,
//       name: 'UB 1.2',
//       nextMatchId: 20513,
//       nextLooserMatchId: 20505,
//       tournamentRoundText: 'UB 1',
//       startTime: 'August 05, 2021',
//       state: 'SCORE_DONE',
//       participants: [
//         {
//           id: 'a3fb4b05-d4ee-4efe-84cf-b500cdbdbbe0',
//           resultText: '2',
//           isWinner: true,
//           status: 'PLAYED',
//           name: 'Towby',
//         },
//         {
//           id: '12046e66-adbf-49d9-98c1-bed16d5ced29',
//           resultText: '1',
//           isWinner: false,
//           status: 'PLAYED',
//           name: 'Alex',
//         },
//       ],
//     },
//     {
//       id: 20515,
//       name: 'Final',
//       nextMatchId: null,
//       nextLooserMatchId: null,
//       tournamentRoundText: 'UB 4',
//       startTime: 'August 05, 2021',
//       state: 'SCORE_DONE',
//       participants: [
//         {
//           id: '3d1a5ddb-85b7-4724-b94d-8747454d66e9',
//           resultText: '2',
//           isWinner: true,
//           status: 'PLAYED',
//           name: 'SeatloN',
//         },
//         {
//           id: 'a3fb4b05-d4ee-4efe-84cf-b500cdbdbbe0',
//           resultText: '1',
//           isWinner: false,
//           status: 'PLAYED',
//           name: 'Towby',
//         },
//       ],
//     },
//     {
//       id: 20508,
//       name: 'UB 1.4',
//       nextMatchId: 20510,
//       nextLooserMatchId: 20503,
//       tournamentRoundText: 'UB 1',
//       startTime: 'August 05, 2021',
//       state: 'SCORE_DONE',
//       participants: [
//         {
//           id: 'dd6c4bff-80da-449c-8bfa-24c835af013a',
//           resultText: '0',
//           isWinner: false,
//           status: 'PLAYED',
//           name: 'OmarDev',
//         },
//         {
//           id: 'a3c107d2-ded2-4f33-85e7-2215805f664b',
//           resultText: '2',
//           isWinner: true,
//           status: 'PLAYED',
//           name: 'BTC',
//         },
//       ],
//     },
//     {
//       id: 20509,
//       name: 'UB 1.1',
//       nextMatchId: 20513,
//       nextLooserMatchId: 20505,
//       tournamentRoundText: 'UB 1',
//       startTime: 'August 05, 2021',
//       state: 'SCORE_DONE',
//       participants: [
//         {
//           id: '8cf422cd-a99d-4184-b2cd-70ee481f46b3',
//           resultText: '2',
//           isWinner: true,
//           status: 'PLAYED',
//           name: 'GlootOne',
//         },
//         {
//           id: 'e1e48aad-5e29-41dc-b904-16f152a7ec74',
//           resultText: '0',
//           isWinner: false,
//           status: 'PLAYED',
//           name: 'spacefudg3',
//         },
//       ],
//     },
//     {
//       id: 20510,
//       name: 'UB 2.2',
//       nextMatchId: 20512,
//       nextLooserMatchId: 20504,
//       tournamentRoundText: 'UB 2',
//       startTime: 'August 05, 2021',
//       state: 'SCORE_DONE',
//       participants: [
//         {
//           id: 'a3c107d2-ded2-4f33-85e7-2215805f664b',
//           resultText: '2',
//           isWinner: true,
//           status: 'PLAYED',
//           name: 'BTC',
//         },
//         {
//           id: '3d1a5ddb-85b7-4724-b94d-8747454d66e9',
//           resultText: '1',
//           isWinner: false,
//           status: 'PLAYED',
//           name: 'SeatloN',
//         },
//       ],
//     },
//     {
//       id: 20511,
//       name: 'UB 1.3',
//       nextMatchId: 20510,
//       nextLooserMatchId: 20503,
//       tournamentRoundText: 'UB 1',
//       startTime: 'August 05, 2021',
//       state: 'SCORE_DONE',
//       participants: [
//         {
//           id: '3d1a5ddb-85b7-4724-b94d-8747454d66e9',
//           resultText: '2',
//           isWinner: true,
//           status: 'PLAYED',
//           name: 'SeatloN',
//         },
//         {
//           id: 'fabb2218-49d6-41a2-874c-d6cd6928df70',
//           resultText: '1',
//           isWinner: false,
//           status: 'PLAYED',
//           name: 'jackieboi',
//         },
//       ],
//     },
//   ],
//   lower: [
//     {
//       id: 20502,
//       name: 'LB Semi Final',
//       nextMatchId: 20515,
//       nextLooserMatchId: null,
//       tournamentRoundText: 'LB 4',
//       startTime: 'August 05, 2021',
//       state: 'SCORE_DONE',
//       participants: [
//         {
//           id: 'a3c107d2-ded2-4f33-85e7-2215805f664b',
//           resultText: '1',
//           isWinner: false,
//           status: 'PLAYED',
//           name: 'BTC',
//         },
//         {
//           id: '3d1a5ddb-85b7-4724-b94d-8747454d66e9',
//           resultText: '2',
//           isWinner: true,
//           status: 'PLAYED',
//           name: 'SeatloN',
//         },
//       ],
//     },
//     {
//       id: 20503,
//       name: 'LB 1.2',
//       nextMatchId: 20506,
//       nextLooserMatchId: null,
//       tournamentRoundText: 'LB 1',
//       startTime: 'August 05, 2021',
//       state: 'SCORE_DONE',
//       participants: [
//         {
//           id: 'dd6c4bff-80da-449c-8bfa-24c835af013a',
//           resultText: '0',
//           isWinner: false,
//           status: 'PLAYED',
//           name: 'OmarDev',
//         },
//         {
//           id: 'fabb2218-49d6-41a2-874c-d6cd6928df70',
//           resultText: '2',
//           isWinner: true,
//           status: 'PLAYED',
//           name: 'jackieboi',
//         },
//       ],
//     },
//     {
//       id: 20504,
//       name: 'LB 2.1',
//       nextMatchId: 20507,
//       nextLooserMatchId: null,
//       tournamentRoundText: 'LB 2',
//       startTime: 'August 05, 2021',
//       state: 'SCORE_DONE',
//       participants: [
//         {
//           id: '3d1a5ddb-85b7-4724-b94d-8747454d66e9',
//           resultText: '2',
//           isWinner: true,
//           status: 'PLAYED',
//           name: 'SeatloN',
//         },
//         {
//           id: 'e1e48aad-5e29-41dc-b904-16f152a7ec74',
//           resultText: '0',
//           isWinner: false,
//           status: 'PLAYED',
//           name: 'spacefudg3',
//         },
//       ],
//     },
//     {
//       id: 20505,
//       name: 'LB 1.1',
//       nextMatchId: 20504,
//       nextLooserMatchId: null,
//       tournamentRoundText: 'LB 1',
//       startTime: 'August 05, 2021',
//       state: 'SCORE_DONE',
//       participants: [
//         {
//           id: 'e1e48aad-5e29-41dc-b904-16f152a7ec74',
//           resultText: '2',
//           isWinner: true,
//           status: 'PLAYED',
//           name: 'spacefudg3',
//         },
//         {
//           id: '12046e66-adbf-49d9-98c1-bed16d5ced29',
//           resultText: '0',
//           isWinner: false,
//           status: 'PLAYED',
//           name: 'Alex',
//         },
//       ],
//     },
//     {
//       id: 20506,
//       name: 'LB 2.2',
//       nextMatchId: 20507,
//       nextLooserMatchId: null,
//       tournamentRoundText: 'LB 2',
//       startTime: 'August 05, 2021',
//       state: 'SCORE_DONE',
//       participants: [
//         {
//           id: 'fabb2218-49d6-41a2-874c-d6cd6928df70',
//           resultText: '1',
//           isWinner: false,
//           status: 'PLAYED',
//           name: 'jackieboi',
//         },
//         {
//           id: '8cf422cd-a99d-4184-b2cd-70ee481f46b3',
//           resultText: '2',
//           isWinner: true,
//           status: 'PLAYED',
//           name: 'GlootOne',
//         },
//       ],
//     },
//     {
//       id: 20507,
//       name: 'LB 3.1',
//       nextMatchId: 20502,
//       nextLooserMatchId: null,
//       tournamentRoundText: 'LB 3',
//       startTime: 'August 05, 2021',
//       state: 'SCORE_DONE',
//       participants: [
//         {
//           id: '3d1a5ddb-85b7-4724-b94d-8747454d66e9',
//           resultText: '2',
//           isWinner: true,
//           status: 'PLAYED',
//           name: 'SeatloN',
//         },
//         {
//           id: '8cf422cd-a99d-4184-b2cd-70ee481f46b3',
//           resultText: '0',
//           isWinner: false,
//           status: 'PLAYED',
//           name: 'GlootOne',
//         },
//       ],
//     },
//   ],
// };
export default {
  upper: [
    {
      id: 389336,
      status: 'Finished',
      has_conflict: false,
      on_solution: false,
      round_id: 6083,
      order: 1,
      code: 'dyFYCPa',
      match_no: 1,
      start_at: null,
      publisher_match_code: null,
      is_losers_match: false,
      nextMatchId: 'kyHcyrL',
      winner_qualifies_to_position: 'home',
      nextLooserMatchId: 'v98g9yX',
      loser_qualifies_to_position: 'home',
      home_qualified_from_status: null,
      home_qualified_from_match_no: null,
      away_qualified_from_status: null,
      away_qualified_from_match_no: null,
      participants: [
        {
          participant_id: 86972,
          participant_type: 'single',
          match_id: 389336,
          side: 'home',
          score: 3,
          isWinner: true,
          original: {
            id: 86972,
            country: 'Algeria',
            participant_name: 'hako-baad-7515',
            reference_number: 'HB19900',
            slug: 'hako-baad-7515',
            is_premium: false,
            avatar:
              'https://gbarena-development.s3.amazonaws.com/users/avatars/defaults/Egypt.user.png',
          },
        },
        {
          participant_id: 62955,
          participant_type: 'single',
          match_id: 389336,
          side: 'away',
          score: 1,
          isWinner: false,
          original: {
            id: 62955,
            country: 'Egypt',
            participant_name:
              'mahmoud',
            reference_number: 'KU83711',
            slug: 'ahmd-4',
            is_premium: false,
            avatar:
              'https://gbarena-development.s3.amazonaws.com/users/avatars/defaults/Egypt.user.png',
          },
        },
      ],
      claims: [],
    },
    {
      id: 389337,
      status: 'Finished',
      has_conflict: false,
      on_solution: false,
      round_id: 6083,
      order: 2,
      code: 'pTtTs6y',
      match_no: 2,
      start_at: null,
      publisher_match_code: null,
      is_losers_match: false,
      nextMatchId: 'kyHcyrL',
      winner_qualifies_to_position: 'away',
      nextLooserMatchId: 'v98g9yX',
      loser_qualifies_to_position: 'away',
      home_qualified_from_status: null,
      home_qualified_from_match_no: null,
      away_qualified_from_status: null,
      away_qualified_from_match_no: null,
      participants: [
        {
          participant_id: 167384,
          participant_type: 'single',
          match_id: 389337,
          side: 'home',
          score: 3,
          isWinner: true,
          original: {
            id: 167384,
            country: 'Egypt',
            participant_name: 'youssef-maged-1161',
            reference_number: 'YM40885',
            slug: 'youssef-maged-1161',
            is_premium: false,
            avatar:
              'https://gbarena-development.s3.amazonaws.com/users/avatars/defaults/Egypt.user.png',
          },
        },
        {
          participant_id: 122850,
          participant_type: 'single',
          match_id: 389337,
          side: 'away',
          score: 2,
          isWinner: false,
          original: {
            id: 122850,
            country: 'Kuwait',
            participant_name: 'Nawaf404',
            reference_number: 'NA65757',
            slug: 'nawaf404',
            is_premium: false,
            avatar:
              'https://gbarena-development.s3.amazonaws.com/users/avatars/defaults/default.png',
          },
        },
      ],
      claims: [],
    },
    {
      id: 389339,
      status: 'Finished',
      has_conflict: false,
      on_solution: false,
      round_id: 6084,
      order: 1,
      code: 'kyHcyrL',
      match_no: 4,
      start_at: null,
      publisher_match_code: null,
      is_losers_match: false,
      nextMatchId: 'Md1oHkm',
      winner_qualifies_to_position: 'home',
      nextLooserMatchId: 'OCgwpWk',
      loser_qualifies_to_position: 'away',
      home_qualified_from_status: 'winner',
      home_qualified_from_match_no: 1,
      away_qualified_from_status: 'winner',
      away_qualified_from_match_no: 2,
      participants: [
        {
          participant_id: 86972,
          participant_type: 'single',
          match_id: 389339,
          side: 'home',
          score: 2,
          isWinner: true,
          original: {
            id: 86972,
            country: 'Algeria',
            participant_name: 'hako-baad-7515',
            reference_number: 'HB19900',
            slug: 'hako-baad-7515',
            is_premium: false,
            avatar:
              'https://gbarena-development.s3.amazonaws.com/users/avatars/defaults/Egypt.user.png',
          },
        },
        {
          participant_id: 167384,
          participant_type: 'single',
          match_id: 389339,
          side: 'away',
          score: 1,
          isWinner: false,
          original: {
            id: 167384,
            country: 'Egypt',
            participant_name: 'youssef-maged-1161',
            reference_number: 'YM40885',
            slug: 'youssef-maged-1161',
            is_premium: false,
            avatar:
              'https://gbarena-development.s3.amazonaws.com/users/avatars/defaults/Egypt.user.png',
          },
        },
      ],
      claims: [],
    },
    {
      id: 389341,
      status: 'Finished',
      has_conflict: false,
      on_solution: false,
      round_id: 6085,
      order: 1,
      code: 'Md1oHkm',
      match_no: 6,
      start_at: null,
      publisher_match_code: null,
      is_losers_match: false,
      nextMatchId: null,
      winner_qualifies_to_position: null,
      nextLooserMatchId: null,
      loser_qualifies_to_position: null,
      home_qualified_from_status: 'winner',
      home_qualified_from_match_no: 4,
      away_qualified_from_status: 'winner',
      away_qualified_from_match_no: 5,
      participants: [
        {
          participant_id: 86972,
          participant_type: 'single',
          match_id: 389341,
          side: 'home',
          score: 3,
          isWinner: true,
          original: {
            id: 86972,
            country: 'Algeria',
            participant_name: 'hako-baad-7515',
            reference_number: 'HB19900',
            slug: 'hako-baad-7515',
            is_premium: false,
            avatar:
              'https://gbarena-development.s3.amazonaws.com/users/avatars/defaults/Egypt.user.png',
          },
        },
        {
          participant_id: 62955,
          participant_type: 'single',
          match_id: 389341,
          side: 'away',
          score: 1,
          isWinner: false,
          original: {
            id: 62955,
            country: 'Egypt',
            participant_name:
              'mahmoud',
            reference_number: 'KU83711',
            slug: 'ahmd-4',
            is_premium: false,
            avatar:
              'https://gbarena-development.s3.amazonaws.com/users/avatars/defaults/Egypt.user.png',
          },
        },
      ],
      claims: [],
    },
  ],
  lower: [
    {
      id: 389340,
      status: 'Finished',
      has_conflict: false,
      on_solution: false,
      round_id: 6084,
      order: 1,
      code: 'OCgwpWk',
      match_no: 5,
      start_at: null,
      is_losers_match: true,
      publisher_match_code: null,
      nextMatchId: 'Md1oHkm',
      winner_qualifies_to_position: 'away',
      nextLooserMatchId: null,
      loser_qualifies_to_position: null,
      home_qualified_from_status: 'winner',
      home_qualified_from_match_no: 3,
      away_qualified_from_status: 'loser',
      away_qualified_from_match_no: 4,
      participants: [
        {
          participant_id: 167384,
          participant_type: 'single',
          match_id: 389340,
          side: 'away',
          score: 1,
          isWinner: false,
          original: {
            id: 167384,
            country: 'Egypt',
            participant_name: 'youssef-maged-1161',
            reference_number: 'YM40885',
            slug: 'youssef-maged-1161',
            is_premium: false,
            avatar:
              'https://gbarena-development.s3.amazonaws.com/users/avatars/defaults/Egypt.user.png',
          },
        },
        {
          participant_id: 62955,
          participant_type: 'single',
          match_id: 389340,
          side: 'home',
          score: 2,
          isWinner: true,
          original: {
            id: 62955,
            country: 'Egypt',
            participant_name:
              'mahmoud',
            reference_number: 'KU83711',
            slug: 'ahmd-4',
            is_premium: false,
            avatar:
              'https://gbarena-development.s3.amazonaws.com/users/avatars/defaults/Egypt.user.png',
          },
        },
      ],
      claims: [],
    },
    {
      id: 389338,
      status: 'Finished',
      has_conflict: false,
      on_solution: false,
      round_id: 6083,
      order: 1,
      code: 'v98g9yX',
      match_no: 3,
      start_at: null,
      is_losers_match: true,
      publisher_match_code: null,
      nextMatchId: 'OCgwpWk',
      winner_qualifies_to_position: 'home',
      nextLooserMatchId: null,
      loser_qualifies_to_position: null,
      home_qualified_from_status: 'loser',
      home_qualified_from_match_no: 1,
      away_qualified_from_status: 'loser',
      away_qualified_from_match_no: 2,
      participants: [
        {
          participant_id: 62955,
          participant_type: 'single',
          match_id: 389338,
          side: 'home',
          score: 2,
          isWinner: true,
          original: {
            id: 62955,
            country: 'Egypt',
            participant_name:
              'mahmoud',
            reference_number: 'KU83711',
            slug: 'ahmd-4',
            is_premium: false,
            avatar:
              'https://gbarena-development.s3.amazonaws.com/users/avatars/defaults/Egypt.user.png',
          },
        },
        {
          participant_id: 122850,
          participant_type: 'single',
          match_id: 389338,
          side: 'away',
          score: 1,
          isWinner: false,
          original: {
            id: 122850,
            country: 'Kuwait',
            participant_name: 'Nawaf404',
            reference_number: 'NA65757',
            slug: 'nawaf404',
            is_premium: false,
            avatar:
              'https://gbarena-development.s3.amazonaws.com/users/avatars/defaults/default.png',
          },
        },
      ],
      claims: [],
    },
  ],
};
