// export default {
//   upper: [
//     {
//       id: 20231,
//       name: 'UB 1.10',
//       nextMatchId: 20242,
//       nextLooserMatchId: 20257,
//       tournamentRoundText: 'UB 1',
//       startTime: null,
//       state: 'WALK_OVER',
//       participants: [
//         {
//           id: '5a2188a4-5e8b-4489-96ba-0140b4342cfd',
//           resultText: null,
//           is_winner: false,
//           status: null,
//         },
//       ],
//     },
//     {
//       id: 20232,
//       name: 'UB 2.8',
//       nextMatchId: 20210,
//       nextLooserMatchId: 20217,
//       tournamentRoundText: 'UB 2',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [],
//     },
//     {
//       id: 20233,
//       name: 'UB 2.7',
//       nextMatchId: 20210,
//       nextLooserMatchId: 20220,
//       tournamentRoundText: 'UB 2',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [
//         {
//           id: '8cfbe1b3-090e-4665-82bb-aff37bebb6f4',
//           resultText: null,
//           is_winner: false,
//           status: null,
//         },
//       ],
//     },
//     {
//       id: 20234,
//       name: 'UB 2.4',
//       nextMatchId: 20207,
//       nextLooserMatchId: 20221,
//       tournamentRoundText: 'UB 2',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [
//         {
//           id: '2ff0c36b-3acc-4c21-90c4-6eeec34e7828',
//           resultText: null,
//           is_winner: false,
//           status: null,
//         },
//       ],
//     },
//     {
//       id: 20235,
//       name: 'UB 4.2',
//       nextMatchId: 20214,
//       nextLooserMatchId: 20223,
//       tournamentRoundText: 'UB 4',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [],
//     },
//     {
//       id: 20236,
//       name: 'UB 1.14',
//       nextMatchId: 20233,
//       nextLooserMatchId: 20261,
//       tournamentRoundText: 'UB 1',
//       startTime: null,
//       state: 'WALK_OVER',
//       participants: [
//         {
//           id: '8cfbe1b3-090e-4665-82bb-aff37bebb6f4',
//           resultText: null,
//           is_winner: false,
//           status: null,
//         },
//       ],
//     },
//     {
//       id: 20237,
//       name: 'UB 4.1',
//       nextMatchId: 20214,
//       nextLooserMatchId: 20229,
//       tournamentRoundText: 'UB 4',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [],
//     },
//     {
//       id: 20238,
//       name: 'UB 2.3',
//       nextMatchId: 20207,
//       nextLooserMatchId: 20227,
//       tournamentRoundText: 'UB 2',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [
//         {
//           id: '781e48d6-2c4d-496d-92e8-6385ea9a7782',
//           resultText: null,
//           is_winner: false,
//           status: null,
//         },
//       ],
//     },
//     {
//       id: 20239,
//       name: 'UB 1.13',
//       nextMatchId: 20233,
//       nextLooserMatchId: 20261,
//       tournamentRoundText: 'UB 1',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [
//         {
//           id: 'c08a1b93-ada2-45b2-8825-f268f167b040',
//           resultText: null,
//           is_winner: false,
//           status: null,
//         },
//         {
//           id: 'b5cd08d2-1596-4c08-9851-75b4f4de7f60',
//           resultText: null,
//           is_winner: false,
//           status: null,
//         },
//       ],
//     },
//     {
//       id: 20240,
//       name: 'UB 2.6',
//       nextMatchId: 20205,
//       nextLooserMatchId: 20218,
//       tournamentRoundText: 'UB 2',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [],
//     },
//     {
//       id: 20241,
//       name: 'UB 1.12',
//       nextMatchId: 20240,
//       nextLooserMatchId: 20254,
//       tournamentRoundText: 'UB 1',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [
//         {
//           id: '0ea06043-7293-4fff-a147-9e47514b6156',
//           resultText: null,
//           is_winner: false,
//           status: null,
//         },
//         {
//           id: '3f7494da-29bb-4594-8a29-7a73080521b5',
//           resultText: null,
//           is_winner: false,
//           status: null,
//         },
//       ],
//     },
//     {
//       id: 20242,
//       name: 'UB 2.5',
//       nextMatchId: 20205,
//       nextLooserMatchId: 20224,
//       tournamentRoundText: 'UB 2',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [
//         {
//           id: '5a2188a4-5e8b-4489-96ba-0140b4342cfd',
//           resultText: null,
//           is_winner: false,
//           status: null,
//         },
//       ],
//     },
//     {
//       id: 20243,
//       name: 'UB 1.11',
//       nextMatchId: 20240,
//       nextLooserMatchId: 20254,
//       tournamentRoundText: 'UB 1',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [
//         {
//           id: 'a601f9ee-1efd-4542-94ab-e62beb690884',
//           resultText: null,
//           is_winner: false,
//           status: null,
//         },
//         {
//           id: '0df5a720-27cd-4ab7-a9b2-1682ac4efe3d',
//           resultText: null,
//           is_winner: false,
//           status: null,
//         },
//       ],
//     },
//     {
//       id: 20244,
//       name: 'UB 2.2',
//       nextMatchId: 20212,
//       nextLooserMatchId: 20226,
//       tournamentRoundText: 'UB 2',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [
//         {
//           id: 'ea7cc04f-aa82-4072-a7c8-397ea3badd6b',
//           resultText: null,
//           is_winner: false,
//           status: null,
//         },
//         {
//           id: '6a602af0-5425-46fd-a3eb-f4d4559717d4',
//           resultText: null,
//           is_winner: false,
//           status: null,
//         },
//       ],
//     },
//     {
//       id: 20245,
//       name: 'UB 1.16',
//       nextMatchId: 20232,
//       nextLooserMatchId: 20260,
//       tournamentRoundText: 'UB 1',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [
//         {
//           id: 'd9edef7d-747f-4516-8dc0-667a2d923785',
//           resultText: null,
//           is_winner: false,
//           status: null,
//         },
//         {
//           id: 'c3116829-63bf-4dfb-8b77-9925eea7a988',
//           resultText: null,
//           is_winner: false,
//           status: null,
//         },
//       ],
//     },
//     {
//       id: 20246,
//       name: 'UB 2.1',
//       nextMatchId: 20212,
//       nextLooserMatchId: 20230,
//       tournamentRoundText: 'UB 2',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [
//         {
//           id: '59c63115-d023-46b7-803b-c95d2b03c802',
//           resultText: null,
//           is_winner: false,
//           status: null,
//         },
//         {
//           id: 'ea43f65a-81ab-4aea-a945-c7bda5ce87e6',
//           resultText: null,
//           is_winner: false,
//           status: null,
//         },
//       ],
//     },
//     {
//       id: 20247,
//       name: 'UB 1.15',
//       nextMatchId: 20232,
//       nextLooserMatchId: 20260,
//       tournamentRoundText: 'UB 1',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [
//         {
//           id: '61da8bf1-9e6f-4435-b8f5-662c3e28b771',
//           resultText: null,
//           is_winner: false,
//           status: null,
//         },
//         {
//           id: 'e37b4d05-d5c6-4561-bac6-9c8c9a0611cd',
//           resultText: null,
//           is_winner: false,
//           status: null,
//         },
//       ],
//     },
//     {
//       id: 20263,
//       name: 'Final',
//       nextMatchId: null,
//       nextLooserMatchId: null,
//       tournamentRoundText: 'UB 6',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [],
//     },
//     {
//       id: 20202,
//       name: 'UB 1.9',
//       nextMatchId: 20242,
//       nextLooserMatchId: 20257,
//       tournamentRoundText: 'UB 1',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [
//         {
//           id: '6c16a503-6577-4f67-9264-935b4dcd5247',
//           resultText: null,
//           is_winner: false,
//           status: null,
//         },
//         {
//           id: '2f9dddd8-eb61-4d73-a34b-a5ba7c6c8311',
//           resultText: null,
//           is_winner: false,
//           status: null,
//         },
//       ],
//     },
//     {
//       id: 20203,
//       name: 'UB 1.8',
//       nextMatchId: 20234,
//       nextLooserMatchId: 20250,
//       tournamentRoundText: 'UB 1',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [
//         {
//           id: '8d4037de-aeb0-4c04-a0b4-868560561d78',
//           resultText: null,
//           is_winner: false,
//           status: null,
//         },
//         {
//           id: '827f34e6-9964-4038-b4a4-663016f18f02',
//           resultText: null,
//           is_winner: false,
//           status: null,
//         },
//       ],
//     },
//     {
//       id: 20204,
//       name: 'UB 1.5',
//       nextMatchId: 20238,
//       nextLooserMatchId: 20252,
//       tournamentRoundText: 'UB 1',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [
//         {
//           id: '0b2ce314-e4ed-4abf-9050-69d51a45e0d7',
//           resultText: null,
//           is_winner: false,
//           status: null,
//         },
//         {
//           id: '7c44871a-fbdd-4861-a690-600ddb427d51',
//           resultText: null,
//           is_winner: false,
//           status: null,
//         },
//       ],
//     },
//     {
//       id: 20205,
//       name: 'UB 3.3',
//       nextMatchId: 20235,
//       nextLooserMatchId: 20222,
//       tournamentRoundText: 'UB 3',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [],
//     },
//     {
//       id: 20206,
//       name: 'UB 1.4',
//       nextMatchId: 20244,
//       nextLooserMatchId: 20248,
//       tournamentRoundText: 'UB 1',
//       startTime: null,
//       state: 'WALK_OVER',
//       participants: [
//         {
//           id: '6a602af0-5425-46fd-a3eb-f4d4559717d4',
//           resultText: null,
//           is_winner: false,
//           status: null,
//         },
//       ],
//     },
//     {
//       id: 20207,
//       name: 'UB 3.2',
//       nextMatchId: 20237,
//       nextLooserMatchId: 20225,
//       tournamentRoundText: 'UB 3',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [],
//     },
//     {
//       id: 20208,
//       name: 'UB 1.7',
//       nextMatchId: 20234,
//       nextLooserMatchId: 20250,
//       tournamentRoundText: 'UB 1',
//       startTime: null,
//       state: 'WALK_OVER',
//       participants: [
//         {
//           id: '2ff0c36b-3acc-4c21-90c4-6eeec34e7828',
//           resultText: null,
//           is_winner: false,
//           status: null,
//         },
//       ],
//     },
//     {
//       id: 20209,
//       name: 'UB 1.6',
//       nextMatchId: 20238,
//       nextLooserMatchId: 20252,
//       tournamentRoundText: 'UB 1',
//       startTime: null,
//       state: 'WALK_OVER',
//       participants: [
//         {
//           id: '781e48d6-2c4d-496d-92e8-6385ea9a7782',
//           resultText: null,
//           is_winner: false,
//           status: null,
//         },
//       ],
//     },
//     {
//       id: 20210,
//       name: 'UB 3.4',
//       nextMatchId: 20235,
//       nextLooserMatchId: 20228,
//       tournamentRoundText: 'UB 3',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [],
//     },
//     {
//       id: 20211,
//       name: 'UB 1.1',
//       nextMatchId: 20246,
//       nextLooserMatchId: 20249,
//       tournamentRoundText: 'UB 1',
//       startTime: null,
//       state: 'WALK_OVER',
//       participants: [
//         {
//           id: '59c63115-d023-46b7-803b-c95d2b03c802',
//           resultText: null,
//           is_winner: false,
//           status: null,
//         },
//       ],
//     },
//     {
//       id: 20212,
//       name: 'UB 3.1',
//       nextMatchId: 20237,
//       nextLooserMatchId: 20219,
//       tournamentRoundText: 'UB 3',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [],
//     },
//     {
//       id: 20213,
//       name: 'UB 1.3',
//       nextMatchId: 20244,
//       nextLooserMatchId: 20248,
//       tournamentRoundText: 'UB 1',
//       startTime: null,
//       state: 'WALK_OVER',
//       participants: [
//         {
//           id: 'ea7cc04f-aa82-4072-a7c8-397ea3badd6b',
//           resultText: null,
//           is_winner: false,
//           status: null,
//         },
//       ],
//     },
//     {
//       id: 20214,
//       name: 'UB Semi Final',
//       nextMatchId: 20263,
//       nextLooserMatchId: 20216,
//       tournamentRoundText: 'UB 5',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [],
//     },
//     {
//       id: 20215,
//       name: 'UB 1.2',
//       nextMatchId: 20246,
//       nextLooserMatchId: 20249,
//       tournamentRoundText: 'UB 1',
//       startTime: null,
//       state: 'WALK_OVER',
//       participants: [
//         {
//           id: 'ea43f65a-81ab-4aea-a945-c7bda5ce87e6',
//           resultText: null,
//           is_winner: false,
//           status: null,
//         },
//       ],
//     },
//   ],
//   lower: [
//     {
//       id: 20224,
//       name: 'LB 2.4',
//       nextMatchId: 20251,
//       nextLooserMatchId: null,
//       tournamentRoundText: 'LB 2',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [],
//     },
//     {
//       id: 20225,
//       name: 'LB 4.2',
//       nextMatchId: 20259,
//       nextLooserMatchId: null,
//       tournamentRoundText: 'LB 4',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [],
//     },
//     {
//       id: 20226,
//       name: 'LB 2.7',
//       nextMatchId: 20255,
//       nextLooserMatchId: null,
//       tournamentRoundText: 'LB 2',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [],
//     },
//     {
//       id: 20227,
//       name: 'LB 2.6',
//       nextMatchId: 20258,
//       nextLooserMatchId: null,
//       tournamentRoundText: 'LB 2',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [],
//     },
//     {
//       id: 20228,
//       name: 'LB 4.4',
//       nextMatchId: 20256,
//       nextLooserMatchId: null,
//       tournamentRoundText: 'LB 4',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [],
//     },
//     {
//       id: 20229,
//       name: 'LB 6.2',
//       nextMatchId: 20262,
//       nextLooserMatchId: null,
//       tournamentRoundText: 'LB 6',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [],
//     },
//     {
//       id: 20230,
//       name: 'LB 2.8',
//       nextMatchId: 20255,
//       nextLooserMatchId: null,
//       tournamentRoundText: 'LB 2',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [],
//     },
//     {
//       id: 20248,
//       name: 'LB 1.2',
//       nextMatchId: 20220,
//       nextLooserMatchId: null,
//       tournamentRoundText: 'LB 1',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [
//         { id: null, resultText: null, is_winner: false, status: 'NO_PARTY' },
//         { id: null, resultText: null, is_winner: false, status: 'NO_PARTY' },
//       ],
//     },
//     {
//       id: 20249,
//       name: 'LB 1.1',
//       nextMatchId: 20217,
//       nextLooserMatchId: null,
//       tournamentRoundText: 'LB 1',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [
//         { id: null, resultText: null, is_winner: false, status: 'NO_PARTY' },
//         { id: null, resultText: null, is_winner: false, status: 'NO_PARTY' },
//       ],
//     },
//     {
//       id: 20250,
//       name: 'LB 1.4',
//       nextMatchId: 20224,
//       nextLooserMatchId: null,
//       tournamentRoundText: 'LB 1',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [
//         { id: null, resultText: null, is_winner: false, status: 'NO_PARTY' },
//       ],
//     },
//     {
//       id: 20251,
//       name: 'LB 3.2',
//       nextMatchId: 20225,
//       nextLooserMatchId: null,
//       tournamentRoundText: 'LB 3',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [],
//     },
//     {
//       id: 20252,
//       name: 'LB 1.3',
//       nextMatchId: 20218,
//       nextLooserMatchId: null,
//       tournamentRoundText: 'LB 1',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [
//         { id: null, resultText: null, is_winner: false, status: 'NO_PARTY' },
//       ],
//     },
//     {
//       id: 20253,
//       name: 'LB 3.1',
//       nextMatchId: 20219,
//       nextLooserMatchId: null,
//       tournamentRoundText: 'LB 3',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [],
//     },
//     {
//       id: 20254,
//       name: 'LB 1.6',
//       nextMatchId: 20227,
//       nextLooserMatchId: null,
//       tournamentRoundText: 'LB 1',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [],
//     },
//     {
//       id: 20255,
//       name: 'LB 3.4',
//       nextMatchId: 20228,
//       nextLooserMatchId: null,
//       tournamentRoundText: 'LB 3',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [],
//     },
//     {
//       id: 20256,
//       name: 'LB 5.2',
//       nextMatchId: 20229,
//       nextLooserMatchId: null,
//       tournamentRoundText: 'LB 5',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [],
//     },
//     {
//       id: 20257,
//       name: 'LB 1.5',
//       nextMatchId: 20221,
//       nextLooserMatchId: null,
//       tournamentRoundText: 'LB 1',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [
//         { id: null, resultText: null, is_winner: false, status: 'NO_PARTY' },
//       ],
//     },
//     {
//       id: 20258,
//       name: 'LB 3.3',
//       nextMatchId: 20222,
//       nextLooserMatchId: null,
//       tournamentRoundText: 'LB 3',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [],
//     },
//     {
//       id: 20259,
//       name: 'LB 5.1',
//       nextMatchId: 20223,
//       nextLooserMatchId: null,
//       tournamentRoundText: 'LB 5',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [],
//     },
//     {
//       id: 20260,
//       name: 'LB 1.8',
//       nextMatchId: 20230,
//       nextLooserMatchId: null,
//       tournamentRoundText: 'LB 1',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [],
//     },
//     {
//       id: 20261,
//       name: 'LB 1.7',
//       nextMatchId: 20226,
//       nextLooserMatchId: null,
//       tournamentRoundText: 'LB 1',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [
//         { id: null, resultText: null, is_winner: false, status: 'NO_PARTY' },
//       ],
//     },
//     {
//       id: 20262,
//       name: 'LB 7.1',
//       nextMatchId: 20216,
//       nextLooserMatchId: null,
//       tournamentRoundText: 'LB 7',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [],
//     },
//     {
//       id: 20216,
//       name: 'LB Semi Final',
//       nextMatchId: 20263,
//       nextLooserMatchId: null,
//       tournamentRoundText: 'LB 8',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [],
//     },
//     {
//       id: 20217,
//       name: 'LB 2.1',
//       nextMatchId: 20253,
//       nextLooserMatchId: null,
//       tournamentRoundText: 'LB 2',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [],
//     },
//     {
//       id: 20218,
//       name: 'LB 2.3',
//       nextMatchId: 20251,
//       nextLooserMatchId: null,
//       tournamentRoundText: 'LB 2',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [],
//     },
//     {
//       id: 20219,
//       name: 'LB 4.1',
//       nextMatchId: 20259,
//       nextLooserMatchId: null,
//       tournamentRoundText: 'LB 4',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [],
//     },
//     {
//       id: 20220,
//       name: 'LB 2.2',
//       nextMatchId: 20253,
//       nextLooserMatchId: null,
//       tournamentRoundText: 'LB 2',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [],
//     },
//     {
//       id: 20221,
//       name: 'LB 2.5',
//       nextMatchId: 20258,
//       nextLooserMatchId: null,
//       tournamentRoundText: 'LB 2',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [],
//     },
//     {
//       id: 20222,
//       name: 'LB 4.3',
//       nextMatchId: 20256,
//       nextLooserMatchId: null,
//       tournamentRoundText: 'LB 4',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [],
//     },
//     {
//       id: 20223,
//       name: 'LB 6.1',
//       nextMatchId: 20262,
//       nextLooserMatchId: null,
//       tournamentRoundText: 'LB 6',
//       startTime: null,
//       state: 'SCHEDULED',
//       participants: [],
//     },
//   ],
// };

export default {
  upper: [
    {
      'id': 454666,
      'status': 'Finished',
      'has_conflict': false,
      'on_solution': false,
      'round_id': 6717,
      'order': 1,
      'code': 'qMgi3zp',
      'match_no': 1,
      'start_at': null,
      'publisher_match_code': null,
      'is_losers_match': false,
      'nextMatchId': 'to9XVty',
      'winner_qualifies_to_position': 'home',
      'nextLooserMatchId': 'uBrxmQh',
      'loser_qualifies_to_position': 'home',
      'home_qualified_from_status': null,
      'home_qualified_from_match_no': null,
      'away_qualified_from_status': null,
      'away_qualified_from_match_no': null,
      'home': {
        'participant_id': 94451,
        'participant_type': 'single',
        'match_id': 454666,
        'side': 'home',
        'score': 3,
        'is_winner': true,
        'tournament_participant': {
          'participant_id': 94451,
          'type': 'single',
          'participant_name': null,
          'is_dummy': false,
          'reference_number': null,
          'supported_required_inputs': null,
        },
        'original': {
          'id': 94451,
          'country': 'Egypt',
          'participant_name': 'ahmed-elsherif-1266',
          'reference_number': 'AE66888',
          'slug': 'ahmed-elsherif-1266',
          'is_premium': false,
          'avatar': 'https:\/\/gbarena-development.s3.amazonaws.com\/users\/avatars\/defaults\/Egypt.user.png',
        },
      },
      'away': {
        'participant_id': 183154,
        'participant_type': 'single',
        'match_id': 454666,
        'side': 'away',
        'score': 1,
        'is_winner': false,
        'tournament_participant': {
          'participant_id': 183154,
          'type': 'single',
          'participant_name': null,
          'is_dummy': false,
          'reference_number': null,
          'supported_required_inputs': null,
        },
        'original': {
          'id': 183154,
          'country': 'Egypt',
          'participant_name': 'khald-asmaaayl-3177',
          'reference_number': 'KA33839',
          'slug': 'khald-asmaaayl-3177',
          'is_premium': false,
          'avatar': 'https:\/\/gbarena-development.s3.amazonaws.com\/users\/avatars\/defaults\/Egypt.user.png',
        },
      },
      'participants': [
        {
          'participant_id': 94451,
          'participant_type': 'single',
          'match_id': 454666,
          'side': 'home',
          'score': 3,
          'is_winner': true,
          'original': {
            'id': 94451,
            'country': 'Egypt',
            'participant_name': 'ahmed-elsherif-1266',
            'reference_number': 'AE66888',
            'slug': 'ahmed-elsherif-1266',
            'is_premium': false,
            'avatar': 'https:\/\/gbarena-development.s3.amazonaws.com\/users\/avatars\/defaults\/Egypt.user.png',
          },
        },
        {
          'participant_id': 183154,
          'participant_type': 'single',
          'match_id': 454666,
          'side': 'away',
          'score': 1,
          'is_winner': false,
          'original': {
            'id': 183154,
            'country': 'Egypt',
            'participant_name': 'khald-asmaaayl-3177',
            'reference_number': 'KA33839',
            'slug': 'khald-asmaaayl-3177',
            'is_premium': false,
            'avatar': 'https:\/\/gbarena-development.s3.amazonaws.com\/users\/avatars\/defaults\/Egypt.user.png',
          },
        },
      ],
      'claims': [],
    },
    {
      'id': 454667,
      'status': 'Finished',
      'has_conflict': false,
      'on_solution': false,
      'round_id': 6717,
      'order': 2,
      'code': 'SJ2CpMP',
      'match_no': 2,
      'start_at': null,
      'publisher_match_code': null,
      'is_losers_match': false,
      'nextMatchId': 'to9XVty',
      'winner_qualifies_to_position': 'away',
      'nextLooserMatchId': 'uBrxmQh',
      'loser_qualifies_to_position': 'away',
      'home_qualified_from_status': null,
      'home_qualified_from_match_no': null,
      'away_qualified_from_status': null,
      'away_qualified_from_match_no': null,
      'home': {
        'participant_id': 35131,
        'participant_type': 'single',
        'match_id': 454667,
        'side': 'home',
        'score': 4,
        'is_winner': true,
        'tournament_participant': {
          'participant_id': 35131,
          'type': 'single',
          'participant_name': null,
          'is_dummy': false,
          'reference_number': null,
          'supported_required_inputs': null,
        },
        'original': {
          'id': 35131,
          'country': 'Egypt',
          'participant_name': 'Ebraheembob2',
          'reference_number': 'EB20481',
          'slug': 'ebraheembob2',
          'is_premium': false,
          'avatar': 'https:\/\/gbarena-development.s3.amazonaws.com\/users\/avatars\/defaults\/default.png',
        },
      },
      'away': {
        'participant_id': 162944,
        'participant_type': 'single',
        'match_id': 454667,
        'side': 'away',
        'score': 1,
        'is_winner': false,
        'tournament_participant': {
          'participant_id': 162944,
          'type': 'single',
          'participant_name': null,
          'is_dummy': false,
          'reference_number': null,
          'supported_required_inputs': null,
        },
        'original': {
          'id': 162944,
          'country': 'Egypt',
          'participant_name': 'khalid-mohamed-8275',
          'reference_number': 'KM60832',
          'slug': 'khalid-mohamed-8275',
          'is_premium': false,
          'avatar': 'https:\/\/gbarena-development.s3.amazonaws.com\/users\/avatars\/defaults\/Egypt.user.png',
        },
      },
      'participants': [
        {
          'participant_id': 35131,
          'participant_type': 'single',
          'match_id': 454667,
          'side': 'home',
          'score': 4,
          'is_winner': true,
          'original': {
            'id': 35131,
            'country': 'Egypt',
            'participant_name': 'Ebraheembob2',
            'reference_number': 'EB20481',
            'slug': 'ebraheembob2',
            'is_premium': false,
            'avatar': 'https:\/\/gbarena-development.s3.amazonaws.com\/users\/avatars\/defaults\/default.png',
          },
        },
        {
          'participant_id': 162944,
          'participant_type': 'single',
          'match_id': 454667,
          'side': 'away',
          'score': 1,
          'is_winner': false,
          'original': {
            'id': 162944,
            'country': 'Egypt',
            'participant_name': 'khalid-mohamed-8275',
            'reference_number': 'KM60832',
            'slug': 'khalid-mohamed-8275',
            'is_premium': false,
            'avatar': 'https:\/\/gbarena-development.s3.amazonaws.com\/users\/avatars\/defaults\/Egypt.user.png',
          },
        },
      ],
      'claims': [],
    },
    {
      'id': 454668,
      'status': 'Finished',
      'has_conflict': false,
      'on_solution': false,
      'round_id': 6717,
      'order': 3,
      'code': 'VMUNTlD',
      'match_no': 3,
      'start_at': null,
      'publisher_match_code': null,
      'is_losers_match': false,
      'nextMatchId': 'eEHhSPU',
      'winner_qualifies_to_position': 'home',
      'nextLooserMatchId': 'LfYR5qB',
      'loser_qualifies_to_position': 'home',
      'home_qualified_from_status': null,
      'home_qualified_from_match_no': null,
      'away_qualified_from_status': null,
      'away_qualified_from_match_no': null,
      'home': {
        'participant_id': 22976,
        'participant_type': 'single',
        'match_id': 454668,
        'side': 'home',
        'score': 3,
        'is_winner': true,
        'tournament_participant': {
          'participant_id': 22976,
          'type': 'single',
          'participant_name': null,
          'is_dummy': false,
          'reference_number': null,
          'supported_required_inputs': null,
        },
        'original': {
          'id': 22976,
          'country': 'Egypt',
          'participant_name': 'hamdy-abogreda',
          'reference_number': 'HA35809',
          'slug': 'hamdy-abogreda',
          'is_premium': false,
          'avatar': 'https:\/\/gbarena-development.s3.amazonaws.com\/users\/avatars\/defaults\/Egypt.user.jpg',
        },
      },
      'away': {
        'participant_id': 4570,
        'participant_type': 'single',
        'match_id': 454668,
        'side': 'away',
        'score': 1,
        'is_winner': false,
        'tournament_participant': {
          'participant_id': 4570,
          'type': 'single',
          'participant_name': null,
          'is_dummy': false,
          'reference_number': null,
          'supported_required_inputs': null,
        },
        'original': {
          'id': 4570,
          'country': 'Egypt',
          'participant_name': 'ahmed-ismail-f\u00e7\u00df',
          'reference_number': 'NQ98106',
          'slug': 'ahmed-ismail-fcss',
          'is_premium': false,
          'avatar': 'https:\/\/gbarena-development.s3.amazonaws.com\/users\/avatars\/defaults\/Egypt.user.png',
        },
      },
      'participants': [
        {
          'participant_id': 22976,
          'participant_type': 'single',
          'match_id': 454668,
          'side': 'home',
          'score': 3,
          'is_winner': true,
          'original': {
            'id': 22976,
            'country': 'Egypt',
            'participant_name': 'hamdy-abogreda',
            'reference_number': 'HA35809',
            'slug': 'hamdy-abogreda',
            'is_premium': false,
            'avatar': 'https:\/\/gbarena-development.s3.amazonaws.com\/users\/avatars\/defaults\/Egypt.user.jpg',
          },
        },
        {
          'participant_id': 4570,
          'participant_type': 'single',
          'match_id': 454668,
          'side': 'away',
          'score': 1,
          'is_winner': false,
          'original': {
            'id': 4570,
            'country': 'Egypt',
            'participant_name': 'ahmed-ismail-f\u00e7\u00df',
            'reference_number': 'NQ98106',
            'slug': 'ahmed-ismail-fcss',
            'is_premium': false,
            'avatar': 'https:\/\/gbarena-development.s3.amazonaws.com\/users\/avatars\/defaults\/Egypt.user.png',
          },
        },
      ],
      'claims': [],
    },
    {
      'id': 454669,
      'status': 'Finished',
      'has_conflict': false,
      'on_solution': false,
      'round_id': 6717,
      'order': 4,
      'code': '4tnn6GC',
      'match_no': 4,
      'start_at': null,
      'publisher_match_code': null,
      'is_losers_match': false,
      'nextMatchId': 'eEHhSPU',
      'winner_qualifies_to_position': 'away',
      'nextLooserMatchId': 'LfYR5qB',
      'loser_qualifies_to_position': 'away',
      'home_qualified_from_status': null,
      'home_qualified_from_match_no': null,
      'away_qualified_from_status': null,
      'away_qualified_from_match_no': null,
      'home': {
        'participant_id': 73293,
        'participant_type': 'single',
        'match_id': 454669,
        'side': 'home',
        'score': 4,
        'is_winner': true,
        'tournament_participant': {
          'participant_id': 73293,
          'type': 'single',
          'participant_name': null,
          'is_dummy': false,
          'reference_number': null,
          'supported_required_inputs': null,
        },
        'original': {
          'id': 73293,
          'country': 'Palestine',
          'participant_name': 'mohammad-aldajne',
          'reference_number': 'MA18870',
          'slug': 'mohammad-aldajne',
          'is_premium': false,
          'avatar': 'https:\/\/gbarena-development.s3.amazonaws.com\/users\/avatars\/Avatar-F-4.9099027320391E%2B20.jpg',
        },
      },
      'away': {
        'participant_id': 63749,
        'participant_type': 'single',
        'match_id': 454669,
        'side': 'away',
        'score': 1,
        'is_winner': false,
        'tournament_participant': {
          'participant_id': 63749,
          'type': 'single',
          'participant_name': null,
          'is_dummy': false,
          'reference_number': null,
          'supported_required_inputs': null,
        },
        'original': {
          'id': 63749,
          'country': 'Egypt',
          'participant_name': 'Loay24',
          'reference_number': 'LO27336',
          'slug': 'loay24',
          'is_premium': false,
          'avatar': 'https:\/\/gbarena-development.s3.amazonaws.com\/users\/avatars\/zJvhWt9uNqScPFe1DTNnGC.jpeg',
        },
      },
      'participants': [
        {
          'participant_id': 73293,
          'participant_type': 'single',
          'match_id': 454669,
          'side': 'home',
          'score': 4,
          'is_winner': true,
          'original': {
            'id': 73293,
            'country': 'Palestine',
            'participant_name': 'mohammad-aldajne',
            'reference_number': 'MA18870',
            'slug': 'mohammad-aldajne',
            'is_premium': false,
            'avatar': 'https:\/\/gbarena-development.s3.amazonaws.com\/users\/avatars\/Avatar-F-4.9099027320391E%2B20.jpg',
          },
        },
        {
          'participant_id': 63749,
          'participant_type': 'single',
          'match_id': 454669,
          'side': 'away',
          'score': 1,
          'is_winner': false,
          'original': {
            'id': 63749,
            'country': 'Egypt',
            'participant_name': 'Loay24',
            'reference_number': 'LO27336',
            'slug': 'loay24',
            'is_premium': false,
            'avatar': 'https:\/\/gbarena-development.s3.amazonaws.com\/users\/avatars\/zJvhWt9uNqScPFe1DTNnGC.jpeg',
          },
        },
      ],
      'claims': [],
    },
    {
      'id': 454672,
      'status': 'To be played',
      'has_conflict': false,
      'on_solution': false,
      'round_id': 6718,
      'order': 1,
      'code': 'to9XVty',
      'match_no': 7,
      'start_at': null,
      'publisher_match_code': null,
      'is_losers_match': false,
      'nextMatchId': 'DDZoR2y',
      'winner_qualifies_to_position': 'home',
      'nextLooserMatchId': 'gGMnCfY',
      'loser_qualifies_to_position': 'away',
      'home_qualified_from_status': 'winner',
      'home_qualified_from_match_no': 1,
      'away_qualified_from_status': 'winner',
      'away_qualified_from_match_no': 2,
      'home': {
        'participant_id': 94451,
        'participant_type': 'single',
        'match_id': 454672,
        'side': 'home',
        'score': null,
        'is_winner': false,
        'tournament_participant': {
          'participant_id': 94451,
          'type': 'single',
          'participant_name': null,
          'is_dummy': false,
          'reference_number': null,
          'supported_required_inputs': null,
        },
        'original': {
          'id': 94451,
          'country': 'Egypt',
          'participant_name': 'ahmed-elsherif-1266',
          'reference_number': 'AE66888',
          'slug': 'ahmed-elsherif-1266',
          'is_premium': false,
          'avatar': 'https:\/\/gbarena-development.s3.amazonaws.com\/users\/avatars\/defaults\/Egypt.user.png',
        },
      },
      'away': {
        'participant_id': 35131,
        'participant_type': 'single',
        'match_id': 454672,
        'side': 'away',
        'score': null,
        'is_winner': false,
        'tournament_participant': {
          'participant_id': 35131,
          'type': 'single',
          'participant_name': null,
          'is_dummy': false,
          'reference_number': null,
          'supported_required_inputs': null,
        },
        'original': {
          'id': 35131,
          'country': 'Egypt',
          'participant_name': 'Ebraheembob2',
          'reference_number': 'EB20481',
          'slug': 'ebraheembob2',
          'is_premium': false,
          'avatar': 'https:\/\/gbarena-development.s3.amazonaws.com\/users\/avatars\/defaults\/default.png',
        },
      },
      'participants': [
        {
          'participant_id': 94451,
          'participant_type': 'single',
          'match_id': 454672,
          'side': 'home',
          'score': null,
          'is_winner': false,
          'original': {
            'id': 94451,
            'country': 'Egypt',
            'participant_name': 'ahmed-elsherif-1266',
            'reference_number': 'AE66888',
            'slug': 'ahmed-elsherif-1266',
            'is_premium': false,
            'avatar': 'https:\/\/gbarena-development.s3.amazonaws.com\/users\/avatars\/defaults\/Egypt.user.png',
          },
        },
        {
          'participant_id': 35131,
          'participant_type': 'single',
          'match_id': 454672,
          'side': 'away',
          'score': null,
          'is_winner': false,
          'original': {
            'id': 35131,
            'country': 'Egypt',
            'participant_name': 'Ebraheembob2',
            'reference_number': 'EB20481',
            'slug': 'ebraheembob2',
            'is_premium': false,
            'avatar': 'https:\/\/gbarena-development.s3.amazonaws.com\/users\/avatars\/defaults\/default.png',
          },
        },
      ],
      'claims': [],
    },
    {
      'id': 454673,
      'status': 'To be played',
      'has_conflict': false,
      'on_solution': false,
      'round_id': 6718,
      'order': 2,
      'code': 'eEHhSPU',
      'match_no': 8,
      'start_at': null,
      'publisher_match_code': null,
      'is_losers_match': false,
      'nextMatchId': 'DDZoR2y',
      'winner_qualifies_to_position': 'away',
      'nextLooserMatchId': 'BdFZznJ',
      'loser_qualifies_to_position': 'away',
      'home_qualified_from_status': 'winner',
      'home_qualified_from_match_no': 3,
      'away_qualified_from_status': 'winner',
      'away_qualified_from_match_no': 4,
      'home': {
        'participant_id': 22976,
        'participant_type': 'single',
        'match_id': 454673,
        'side': 'home',
        'score': null,
        'is_winner': false,
        'tournament_participant': {
          'participant_id': 22976,
          'type': 'single',
          'participant_name': null,
          'is_dummy': false,
          'reference_number': null,
          'supported_required_inputs': null,
        },
        'original': {
          'id': 22976,
          'country': 'Egypt',
          'participant_name': 'hamdy-abogreda',
          'reference_number': 'HA35809',
          'slug': 'hamdy-abogreda',
          'is_premium': false,
          'avatar': 'https:\/\/gbarena-development.s3.amazonaws.com\/users\/avatars\/defaults\/Egypt.user.jpg',
        },
      },
      'away': {
        'participant_id': 73293,
        'participant_type': 'single',
        'match_id': 454673,
        'side': 'away',
        'score': null,
        'is_winner': false,
        'tournament_participant': {
          'participant_id': 73293,
          'type': 'single',
          'participant_name': null,
          'is_dummy': false,
          'reference_number': null,
          'supported_required_inputs': null,
        },
        'original': {
          'id': 73293,
          'country': 'Palestine',
          'participant_name': 'mohammad-aldajne',
          'reference_number': 'MA18870',
          'slug': 'mohammad-aldajne',
          'is_premium': false,
          'avatar': 'https:\/\/gbarena-development.s3.amazonaws.com\/users\/avatars\/Avatar-F-4.9099027320391E%2B20.jpg',
        },
      },
      'participants': [
        {
          'participant_id': 73293,
          'participant_type': 'single',
          'match_id': 454673,
          'side': 'away',
          'score': null,
          'is_winner': false,
          'original': {
            'id': 73293,
            'country': 'Palestine',
            'participant_name': 'mohammad-aldajne',
            'reference_number': 'MA18870',
            'slug': 'mohammad-aldajne',
            'is_premium': false,
            'avatar': 'https:\/\/gbarena-development.s3.amazonaws.com\/users\/avatars\/Avatar-F-4.9099027320391E%2B20.jpg',
          },
        },
      ],
      'claims': [],
    },
    {
      'id': 454676,
      'status': 'To be played',
      'has_conflict': false,
      'on_solution': false,
      'round_id': 6719,
      'order': 1,
      'code': 'DDZoR2y',
      'match_no': 11,
      'start_at': null,
      'publisher_match_code': null,
      'is_losers_match': false,
      'nextMatchId': 'BdoFfWA',
      'winner_qualifies_to_position': 'home',
      'nextLooserMatchId': '6EOZErD',
      'loser_qualifies_to_position': 'away',
      'home_qualified_from_status': 'winner',
      'home_qualified_from_match_no': 7,
      'away_qualified_from_status': 'winner',
      'away_qualified_from_match_no': 8,
      'home': null,
      'away': null,
      'participants': [],
      'claims': [],
    },
    {
      'id': 454678,
      'status': 'To be played',
      'has_conflict': false,
      'on_solution': false,
      'round_id': 6720,
      'order': 1,
      'code': 'BdoFfWA',
      'match_no': 13,
      'start_at': null,
      'publisher_match_code': null,
      'is_losers_match': false,
      'nextMatchId': null,
      'winner_qualifies_to_position': null,
      'nextLooserMatchId': null,
      'loser_qualifies_to_position': null,
      'home_qualified_from_status': 'winner',
      'home_qualified_from_match_no': 11,
      'away_qualified_from_status': 'winner',
      'away_qualified_from_match_no': 14,
      'home': null,
      'away': null,
      'participants': [],
      'claims': [],
    },
  ],
  lower: [
    {
      'id': 454670,
      'status': 'To be played',
      'has_conflict': false,
      'on_solution': false,
      'round_id': 6717,
      'order': 1,
      'code': 'uBrxmQh',
      'match_no': 5,
      'start_at': null,
      'is_losers_match': true,
      'publisher_match_code': null,
      'nextMatchId': 'BdFZznJ',
      'winner_qualifies_to_position': 'home',
      'nextLooserMatchId': null,
      'loser_qualifies_to_position': null,
      'home_qualified_from_status': 'loser',
      'home_qualified_from_match_no': 1,
      'away_qualified_from_status': 'loser',
      'away_qualified_from_match_no': 2,
      'home': {
        'participant_id': 183154,
        'participant_type': 'single',
        'match_id': 454670,
        'side': 'home',
        'score': null,
        'is_winner': false,
        'tournament_participant': {
          'participant_id': 183154,
          'type': 'single',
          'participant_name': null,
          'is_dummy': false,
          'reference_number': null,
          'supported_required_inputs': null,
        },
        'original': {
          'id': 183154,
          'country': 'Egypt',
          'participant_name': 'khald-asmaaayl-3177',
          'reference_number': 'KA33839',
          'slug': 'khald-asmaaayl-3177',
          'is_premium': false,
          'avatar': 'https:\/\/gbarena-development.s3.amazonaws.com\/users\/avatars\/defaults\/Egypt.user.png',
        },
      },
      'away': {
        'participant_id': 162944,
        'participant_type': 'single',
        'match_id': 454670,
        'side': 'away',
        'score': null,
        'is_winner': false,
        'tournament_participant': {
          'participant_id': 162944,
          'type': 'single',
          'participant_name': null,
          'is_dummy': false,
          'reference_number': null,
          'supported_required_inputs': null,
        },
        'original': {
          'id': 162944,
          'country': 'Egypt',
          'participant_name': 'khalid-mohamed-8275',
          'reference_number': 'KM60832',
          'slug': 'khalid-mohamed-8275',
          'is_premium': false,
          'avatar': 'https:\/\/gbarena-development.s3.amazonaws.com\/users\/avatars\/defaults\/Egypt.user.png',
        },
      },
      'participants': [
        {
          'participant_id': 183154,
          'participant_type': 'single',
          'match_id': 454670,
          'side': 'home',
          'score': null,
          'is_winner': false,
          'original': {
            'id': 183154,
            'country': 'Egypt',
            'participant_name': 'khald-asmaaayl-3177',
            'reference_number': 'KA33839',
            'slug': 'khald-asmaaayl-3177',
            'is_premium': false,
            'avatar': 'https:\/\/gbarena-development.s3.amazonaws.com\/users\/avatars\/defaults\/Egypt.user.png',
          },
        },
        {
          'participant_id': 162944,
          'participant_type': 'single',
          'match_id': 454670,
          'side': 'away',
          'score': null,
          'is_winner': false,
          'original': {
            'id': 162944,
            'country': 'Egypt',
            'participant_name': 'khalid-mohamed-8275',
            'reference_number': 'KM60832',
            'slug': 'khalid-mohamed-8275',
            'is_premium': false,
            'avatar': 'https:\/\/gbarena-development.s3.amazonaws.com\/users\/avatars\/defaults\/Egypt.user.png',
          },
        },
      ],
      'claims': [],
    },
    {
      'id': 454671,
      'status': 'To be played',
      'has_conflict': false,
      'on_solution': false,
      'round_id': 6717,
      'order': 2,
      'code': 'LfYR5qB',
      'match_no': 6,
      'start_at': null,
      'is_losers_match': true,
      'publisher_match_code': null,
      'nextMatchId': 'gGMnCfY',
      'winner_qualifies_to_position': 'home',
      'nextLooserMatchId': null,
      'loser_qualifies_to_position': null,
      'home_qualified_from_status': 'loser',
      'home_qualified_from_match_no': 3,
      'away_qualified_from_status': 'loser',
      'away_qualified_from_match_no': 4,
      'home': {
        'participant_id': 4570,
        'participant_type': 'single',
        'match_id': 454671,
        'side': 'home',
        'score': null,
        'is_winner': false,
        'tournament_participant': {
          'participant_id': 4570,
          'type': 'single',
          'participant_name': null,
          'is_dummy': false,
          'reference_number': null,
          'supported_required_inputs': null,
        },
        'original': {
          'id': 4570,
          'country': 'Egypt',
          'participant_name': 'ahmed-ismail-f\u00e7\u00df',
          'reference_number': 'NQ98106',
          'slug': 'ahmed-ismail-fcss',
          'is_premium': false,
          'avatar': 'https:\/\/gbarena-development.s3.amazonaws.com\/users\/avatars\/defaults\/Egypt.user.png',
        },
      },
      'away': {
        'participant_id': 63749,
        'participant_type': 'single',
        'match_id': 454671,
        'side': 'away',
        'score': null,
        'is_winner': false,
        'tournament_participant': {
          'participant_id': 63749,
          'type': 'single',
          'participant_name': null,
          'is_dummy': false,
          'reference_number': null,
          'supported_required_inputs': null,
        },
        'original': {
          'id': 63749,
          'country': 'Egypt',
          'participant_name': 'Loay24',
          'reference_number': 'LO27336',
          'slug': 'loay24',
          'is_premium': false,
          'avatar': 'https:\/\/gbarena-development.s3.amazonaws.com\/users\/avatars\/zJvhWt9uNqScPFe1DTNnGC.jpeg',
        },
      },
      'participants': [
        {
          'participant_id': 4570,
          'participant_type': 'single',
          'match_id': 454671,
          'side': 'home',
          'score': null,
          'is_winner': false,
          'original': {
            'id': 4570,
            'country': 'Egypt',
            'participant_name': 'ahmed-ismail-f\u00e7\u00df',
            'reference_number': 'NQ98106',
            'slug': 'ahmed-ismail-fcss',
            'is_premium': false,
            'avatar': 'https:\/\/gbarena-development.s3.amazonaws.com\/users\/avatars\/defaults\/Egypt.user.png',
          },
        },
        {
          'participant_id': 63749,
          'participant_type': 'single',
          'match_id': 454671,
          'side': 'away',
          'score': null,
          'is_winner': false,
          'original': {
            'id': 63749,
            'country': 'Egypt',
            'participant_name': 'Loay24',
            'reference_number': 'LO27336',
            'slug': 'loay24',
            'is_premium': false,
            'avatar': 'https:\/\/gbarena-development.s3.amazonaws.com\/users\/avatars\/zJvhWt9uNqScPFe1DTNnGC.jpeg',
          },
        },
      ],
      'claims': [],
    },
    {
      'id': 454674,
      'status': 'To be played',
      'has_conflict': false,
      'on_solution': false,
      'round_id': 6718,
      'order': 1,
      'code': 'BdFZznJ',
      'match_no': 9,
      'start_at': null,
      'is_losers_match': true,
      'publisher_match_code': null,
      'nextMatchId': 'phGIfOk',
      'winner_qualifies_to_position': 'home',
      'nextLooserMatchId': null,
      'loser_qualifies_to_position': null,
      'home_qualified_from_status': 'winner',
      'home_qualified_from_match_no': 5,
      'away_qualified_from_status': 'loser',
      'away_qualified_from_match_no': 8,
      'home': null,
      'away': null,
      'participants': [],
      'claims': [],
    },
    {
      'id': 454675,
      'status': 'To be played',
      'has_conflict': false,
      'on_solution': false,
      'round_id': 6718,
      'order': 2,
      'code': 'gGMnCfY',
      'match_no': 10,
      'start_at': null,
      'is_losers_match': true,
      'publisher_match_code': null,
      'nextMatchId': 'phGIfOk',
      'winner_qualifies_to_position': 'away',
      'nextLooserMatchId': null,
      'loser_qualifies_to_position': null,
      'home_qualified_from_status': 'winner',
      'home_qualified_from_match_no': 6,
      'away_qualified_from_status': 'loser',
      'away_qualified_from_match_no': 7,
      'home': null,
      'away': null,
      'participants': [],
      'claims': [],
    },
    {
      'id': 454677,
      'status': 'To be played',
      'has_conflict': false,
      'on_solution': false,
      'round_id': 6719,
      'order': 1,
      'code': 'phGIfOk',
      'match_no': 12,
      'start_at': null,
      'is_losers_match': true,
      'publisher_match_code': null,
      'nextMatchId': '6EOZErD',
      'winner_qualifies_to_position': 'home',
      'nextLooserMatchId': null,
      'loser_qualifies_to_position': null,
      'home_qualified_from_status': 'winner',
      'home_qualified_from_match_no': 9,
      'away_qualified_from_status': 'winner',
      'away_qualified_from_match_no': 10,
      'home': null,
      'away': null,
      'participants': [],
      'claims': [],
    },
    {
      'id': 454679,
      'status': 'To be played',
      'has_conflict': false,
      'on_solution': false,
      'round_id': 6720,
      'order': 1,
      'code': '6EOZErD',
      'match_no': 14,
      'start_at': null,
      'is_losers_match': true,
      'publisher_match_code': null,
      'nextMatchId': 'BdoFfWA',
      'winner_qualifies_to_position': 'away',
      'nextLooserMatchId': null,
      'loser_qualifies_to_position': null,
      'home_qualified_from_status': 'winner',
      'home_qualified_from_match_no': 12,
      'away_qualified_from_status': 'loser',
      'away_qualified_from_match_no': 11,
      'home': null,
      'away': null,
      'participants': [],
      'claims': [],
    },
  ],
};

/// /
