// export default {
//   upper: [
//     {
//       id: 20512,
//       name: 'UB Semi Final',
//       nextMatchId: 20515,
//       nextLooserMatchId: 20502,
//       tournamentRoundText: 'UB 3',
//       startTime: 'August 05, 2021',
//       state: 'SCORE_DONE',
//       participants: [
//         {
//           id: 'a3c107d2-ded2-4f33-85e7-2215805f664b',
//           resultText: '0',
//           is_winner: false,
//           status: 'PLAYED',
//           name: 'BTC',
//         },
//         {
//           id: 'a3fb4b05-d4ee-4efe-84cf-b500cdbdbbe0',
//           resultText: '2',
//           is_winner: true,
//           status: 'PLAYED',
//           name: 'Towby',
//         },
//       ],
//     },
//     {
//       id: 20513,
//       name: 'UB 2.1',
//       nextMatchId: 20512,
//       nextLooserMatchId: 20506,
//       tournamentRoundText: 'UB 2',
//       startTime: 'August 05, 2021',
//       state: 'SCORE_DONE',
//       participants: [
//         {
//           id: '8cf422cd-a99d-4184-b2cd-70ee481f46b3',
//           resultText: '0',
//           is_winner: false,
//           status: 'PLAYED',
//           name: 'GlootOne',
//         },
//         {
//           id: 'a3fb4b05-d4ee-4efe-84cf-b500cdbdbbe0',
//           resultText: '2',
//           is_winner: true,
//           status: 'PLAYED',
//           name: 'Towby',
//         },
//       ],
//     },
//     {
//       id: 20514,
//       name: 'UB 1.2',
//       nextMatchId: 20513,
//       nextLooserMatchId: 20505,
//       tournamentRoundText: 'UB 1',
//       startTime: 'August 05, 2021',
//       state: 'SCORE_DONE',
//       participants: [
//         {
//           id: 'a3fb4b05-d4ee-4efe-84cf-b500cdbdbbe0',
//           resultText: '2',
//           is_winner: true,
//           status: 'PLAYED',
//           name: 'Towby',
//         },
//         {
//           id: '12046e66-adbf-49d9-98c1-bed16d5ced29',
//           resultText: '1',
//           is_winner: false,
//           status: 'PLAYED',
//           name: 'Alex',
//         },
//       ],
//     },
//     {
//       id: 20515,
//       name: 'Final',
//       nextMatchId: null,
//       nextLooserMatchId: null,
//       tournamentRoundText: 'UB 4',
//       startTime: 'August 05, 2021',
//       state: 'SCORE_DONE',
//       participants: [
//         {
//           id: '3d1a5ddb-85b7-4724-b94d-8747454d66e9',
//           resultText: '2',
//           is_winner: true,
//           status: 'PLAYED',
//           name: 'SeatloN',
//         },
//         {
//           id: 'a3fb4b05-d4ee-4efe-84cf-b500cdbdbbe0',
//           resultText: '1',
//           is_winner: false,
//           status: 'PLAYED',
//           name: 'Towby',
//         },
//       ],
//     },
//     {
//       id: 20508,
//       name: 'UB 1.4',
//       nextMatchId: 20510,
//       nextLooserMatchId: 20503,
//       tournamentRoundText: 'UB 1',
//       startTime: 'August 05, 2021',
//       state: 'SCORE_DONE',
//       participants: [
//         {
//           id: 'dd6c4bff-80da-449c-8bfa-24c835af013a',
//           resultText: '0',
//           is_winner: false,
//           status: 'PLAYED',
//           name: 'OmarDev',
//         },
//         {
//           id: 'a3c107d2-ded2-4f33-85e7-2215805f664b',
//           resultText: '2',
//           is_winner: true,
//           status: 'PLAYED',
//           name: 'BTC',
//         },
//       ],
//     },
//     {
//       id: 20509,
//       name: 'UB 1.1',
//       nextMatchId: 20513,
//       nextLooserMatchId: 20505,
//       tournamentRoundText: 'UB 1',
//       startTime: 'August 05, 2021',
//       state: 'SCORE_DONE',
//       participants: [
//         {
//           id: '8cf422cd-a99d-4184-b2cd-70ee481f46b3',
//           resultText: '2',
//           is_winner: true,
//           status: 'PLAYED',
//           name: 'GlootOne',
//         },
//         {
//           id: 'e1e48aad-5e29-41dc-b904-16f152a7ec74',
//           resultText: '0',
//           is_winner: false,
//           status: 'PLAYED',
//           name: 'spacefudg3',
//         },
//       ],
//     },
//     {
//       id: 20510,
//       name: 'UB 2.2',
//       nextMatchId: 20512,
//       nextLooserMatchId: 20504,
//       tournamentRoundText: 'UB 2',
//       startTime: 'August 05, 2021',
//       state: 'SCORE_DONE',
//       participants: [
//         {
//           id: 'a3c107d2-ded2-4f33-85e7-2215805f664b',
//           resultText: '2',
//           is_winner: true,
//           status: 'PLAYED',
//           name: 'BTC',
//         },
//         {
//           id: '3d1a5ddb-85b7-4724-b94d-8747454d66e9',
//           resultText: '1',
//           is_winner: false,
//           status: 'PLAYED',
//           name: 'SeatloN',
//         },
//       ],
//     },
//     {
//       id: 20511,
//       name: 'UB 1.3',
//       nextMatchId: 20510,
//       nextLooserMatchId: 20503,
//       tournamentRoundText: 'UB 1',
//       startTime: 'August 05, 2021',
//       state: 'SCORE_DONE',
//       participants: [
//         {
//           id: '3d1a5ddb-85b7-4724-b94d-8747454d66e9',
//           resultText: '2',
//           is_winner: true,
//           status: 'PLAYED',
//           name: 'SeatloN',
//         },
//         {
//           id: 'fabb2218-49d6-41a2-874c-d6cd6928df70',
//           resultText: '1',
//           is_winner: false,
//           status: 'PLAYED',
//           name: 'jackieboi',
//         },
//       ],
//     },
//   ],
//   lower: [
//     {
//       id: 20502,
//       name: 'LB Semi Final',
//       nextMatchId: 20515,
//       nextLooserMatchId: null,
//       tournamentRoundText: 'LB 4',
//       startTime: 'August 05, 2021',
//       state: 'SCORE_DONE',
//       participants: [
//         {
//           id: 'a3c107d2-ded2-4f33-85e7-2215805f664b',
//           resultText: '1',
//           is_winner: false,
//           status: 'PLAYED',
//           name: 'BTC',
//         },
//         {
//           id: '3d1a5ddb-85b7-4724-b94d-8747454d66e9',
//           resultText: '2',
//           is_winner: true,
//           status: 'PLAYED',
//           name: 'SeatloN',
//         },
//       ],
//     },
//     {
//       id: 20503,
//       name: 'LB 1.2',
//       nextMatchId: 20506,
//       nextLooserMatchId: null,
//       tournamentRoundText: 'LB 1',
//       startTime: 'August 05, 2021',
//       state: 'SCORE_DONE',
//       participants: [
//         {
//           id: 'dd6c4bff-80da-449c-8bfa-24c835af013a',
//           resultText: '0',
//           is_winner: false,
//           status: 'PLAYED',
//           name: 'OmarDev',
//         },
//         {
//           id: 'fabb2218-49d6-41a2-874c-d6cd6928df70',
//           resultText: '2',
//           is_winner: true,
//           status: 'PLAYED',
//           name: 'jackieboi',
//         },
//       ],
//     },
//     {
//       id: 20504,
//       name: 'LB 2.1',
//       nextMatchId: 20507,
//       nextLooserMatchId: null,
//       tournamentRoundText: 'LB 2',
//       startTime: 'August 05, 2021',
//       state: 'SCORE_DONE',
//       participants: [
//         {
//           id: '3d1a5ddb-85b7-4724-b94d-8747454d66e9',
//           resultText: '2',
//           is_winner: true,
//           status: 'PLAYED',
//           name: 'SeatloN',
//         },
//         {
//           id: 'e1e48aad-5e29-41dc-b904-16f152a7ec74',
//           resultText: '0',
//           is_winner: false,
//           status: 'PLAYED',
//           name: 'spacefudg3',
//         },
//       ],
//     },
//     {
//       id: 20505,
//       name: 'LB 1.1',
//       nextMatchId: 20504,
//       nextLooserMatchId: null,
//       tournamentRoundText: 'LB 1',
//       startTime: 'August 05, 2021',
//       state: 'SCORE_DONE',
//       participants: [
//         {
//           id: 'e1e48aad-5e29-41dc-b904-16f152a7ec74',
//           resultText: '2',
//           is_winner: true,
//           status: 'PLAYED',
//           name: 'spacefudg3',
//         },
//         {
//           id: '12046e66-adbf-49d9-98c1-bed16d5ced29',
//           resultText: '0',
//           is_winner: false,
//           status: 'PLAYED',
//           name: 'Alex',
//         },
//       ],
//     },
//     {
//       id: 20506,
//       name: 'LB 2.2',
//       nextMatchId: 20507,
//       nextLooserMatchId: null,
//       tournamentRoundText: 'LB 2',
//       startTime: 'August 05, 2021',
//       state: 'SCORE_DONE',
//       participants: [
//         {
//           id: 'fabb2218-49d6-41a2-874c-d6cd6928df70',
//           resultText: '1',
//           is_winner: false,
//           status: 'PLAYED',
//           name: 'jackieboi',
//         },
//         {
//           id: '8cf422cd-a99d-4184-b2cd-70ee481f46b3',
//           resultText: '2',
//           is_winner: true,
//           status: 'PLAYED',
//           name: 'GlootOne',
//         },
//       ],
//     },
//     {
//       id: 20507,
//       name: 'LB 3.1',
//       nextMatchId: 20502,
//       nextLooserMatchId: null,
//       tournamentRoundText: 'LB 3',
//       startTime: 'August 05, 2021',
//       state: 'SCORE_DONE',
//       participants: [
//         {
//           id: '3d1a5ddb-85b7-4724-b94d-8747454d66e9',
//           resultText: '2',
//           is_winner: true,
//           status: 'PLAYED',
//           name: 'SeatloN',
//         },
//         {
//           id: '8cf422cd-a99d-4184-b2cd-70ee481f46b3',
//           resultText: '0',
//           is_winner: false,
//           status: 'PLAYED',
//           name: 'GlootOne',
//         },
//       ],
//     },
//   ],
// };
export default {
  // upper: [
  //   {
  //     id: 389336,
  //     status: 'Finished',
  //     has_conflict: false,
  //     on_solution: false,
  //     round_id: 6083,
  //     order: 1,
  //     code: 'dyFYCPa',
  //     match_no: 1,
  //     start_at: null,
  //     publisher_match_code: null,
  //     is_losers_match: false,
  //     nextMatchId: 'kyHcyrL',
  //     winner_qualifies_to_position: 'home',
  //     nextLooserMatchId: 'v98g9yX',
  //     loser_qualifies_to_position: 'home',
  //     home_qualified_from_status: null,
  //     home_qualified_from_match_no: null,
  //     away_qualified_from_status: null,
  //     away_qualified_from_match_no: null,
  //     participants: [
  //       {
  //         participant_id: 86972,
  //         participant_type: 'single',
  //         match_id: 389336,
  //         side: 'home',
  //         score: 3,
  //         is_winner: true,
  //         original: {
  //           id: 86972,
  //           country: 'Algeria',
  //           participant_name: 'hako-baad-7515',
  //           reference_number: 'HB19900',
  //           slug: 'hako-baad-7515',
  //           is_premium: false,
  //           avatar:
  //             'https://gbarena-development.s3.amazonaws.com/users/avatars/defaults/Egypt.user.png',
  //         },
  //       },
  //       {
  //         participant_id: 62955,
  //         participant_type: 'single',
  //         match_id: 389336,
  //         side: 'away',
  //         score: 1,
  //         is_winner: false,
  //         original: {
  //           id: 62955,
  //           country: 'Egypt',
  //           participant_name:
  //             'mahmoud',
  //           reference_number: 'KU83711',
  //           slug: 'ahmd-4',
  //           is_premium: false,
  //           avatar:
  //             'https://gbarena-development.s3.amazonaws.com/users/avatars/defaults/Egypt.user.png',
  //         },
  //       },
  //     ],
  //     claims: [],
  //   },
  //   {
  //     id: 389337,
  //     status: 'Finished',
  //     has_conflict: false,
  //     on_solution: false,
  //     round_id: 6083,
  //     order: 2,
  //     code: 'pTtTs6y',
  //     match_no: 2,
  //     start_at: null,
  //     publisher_match_code: null,
  //     is_losers_match: false,
  //     nextMatchId: 'kyHcyrL',
  //     winner_qualifies_to_position: 'away',
  //     nextLooserMatchId: 'v98g9yX',
  //     loser_qualifies_to_position: 'away',
  //     home_qualified_from_status: null,
  //     home_qualified_from_match_no: null,
  //     away_qualified_from_status: null,
  //     away_qualified_from_match_no: null,
  //     participants: [
  //       {
  //         participant_id: 167384,
  //         participant_type: 'single',
  //         match_id: 389337,
  //         side: 'home',
  //         score: 3,
  //         is_winner: true,
  //         original: {
  //           id: 167384,
  //           country: 'Egypt',
  //           participant_name: 'youssef-maged-1161',
  //           reference_number: 'YM40885',
  //           slug: 'youssef-maged-1161',
  //           is_premium: false,
  //           avatar:
  //             'https://gbarena-development.s3.amazonaws.com/users/avatars/defaults/Egypt.user.png',
  //         },
  //       },
  //       {
  //         participant_id: 122850,
  //         participant_type: 'single',
  //         match_id: 389337,
  //         side: 'away',
  //         score: 2,
  //         is_winner: false,
  //         original: {
  //           id: 122850,
  //           country: 'Kuwait',
  //           participant_name: 'Nawaf404',
  //           reference_number: 'NA65757',
  //           slug: 'nawaf404',
  //           is_premium: false,
  //           avatar:
  //             'https://gbarena-development.s3.amazonaws.com/users/avatars/defaults/default.png',
  //         },
  //       },
  //     ],
  //     claims: [],
  //   },
  //   {
  //     id: 389339,
  //     status: 'Finished',
  //     has_conflict: false,
  //     on_solution: false,
  //     round_id: 6084,
  //     order: 1,
  //     code: 'kyHcyrL',
  //     match_no: 4,
  //     start_at: null,
  //     publisher_match_code: null,
  //     is_losers_match: false,
  //     nextMatchId: 'Md1oHkm',
  //     winner_qualifies_to_position: 'home',
  //     nextLooserMatchId: 'OCgwpWk',
  //     loser_qualifies_to_position: 'away',
  //     home_qualified_from_status: 'winner',
  //     home_qualified_from_match_no: 1,
  //     away_qualified_from_status: 'winner',
  //     away_qualified_from_match_no: 2,
  //     participants: [
  //       {
  //         participant_id: 86972,
  //         participant_type: 'single',
  //         match_id: 389339,
  //         side: 'home',
  //         score: 2,
  //         is_winner: true,
  //         original: {
  //           id: 86972,
  //           country: 'Algeria',
  //           participant_name: 'hako-baad-7515',
  //           reference_number: 'HB19900',
  //           slug: 'hako-baad-7515',
  //           is_premium: false,
  //           avatar:
  //             'https://gbarena-development.s3.amazonaws.com/users/avatars/defaults/Egypt.user.png',
  //         },
  //       },
  //       {
  //         participant_id: 167384,
  //         participant_type: 'single',
  //         match_id: 389339,
  //         side: 'away',
  //         score: 1,
  //         is_winner: false,
  //         original: {
  //           id: 167384,
  //           country: 'Egypt',
  //           participant_name: 'youssef-maged-1161',
  //           reference_number: 'YM40885',
  //           slug: 'youssef-maged-1161',
  //           is_premium: false,
  //           avatar:
  //             'https://gbarena-development.s3.amazonaws.com/users/avatars/defaults/Egypt.user.png',
  //         },
  //       },
  //     ],
  //     claims: [],
  //   },
  //   {
  //     id: 389341,
  //     status: 'Finished',
  //     has_conflict: false,
  //     on_solution: false,
  //     round_id: 6085,
  //     order: 1,
  //     code: 'Md1oHkm',
  //     match_no: 6,
  //     start_at: null,
  //     publisher_match_code: null,
  //     is_losers_match: false,
  //     nextMatchId: null,
  //     winner_qualifies_to_position: null,
  //     nextLooserMatchId: null,
  //     loser_qualifies_to_position: null,
  //     home_qualified_from_status: 'winner',
  //     home_qualified_from_match_no: 4,
  //     away_qualified_from_status: 'winner',
  //     away_qualified_from_match_no: 5,
  //     participants: [
  //       {
  //         participant_id: 86972,
  //         participant_type: 'single',
  //         match_id: 389341,
  //         side: 'home',
  //         score: 3,
  //         is_winner: true,
  //         original: {
  //           id: 86972,
  //           country: 'Algeria',
  //           participant_name: 'hako-baad-7515',
  //           reference_number: 'HB19900',
  //           slug: 'hako-baad-7515',
  //           is_premium: false,
  //           avatar:
  //             'https://gbarena-development.s3.amazonaws.com/users/avatars/defaults/Egypt.user.png',
  //         },
  //       },
  //       {
  //         participant_id: 62955,
  //         participant_type: 'single',
  //         match_id: 389341,
  //         side: 'away',
  //         score: 1,
  //         is_winner: false,
  //         original: {
  //           id: 62955,
  //           country: 'Egypt',
  //           participant_name:
  //             'mahmoud',
  //           reference_number: 'KU83711',
  //           slug: 'ahmd-4',
  //           is_premium: false,
  //           avatar:
  //             'https://gbarena-development.s3.amazonaws.com/users/avatars/defaults/Egypt.user.png',
  //         },
  //       },
  //     ],
  //     claims: [],
  //   },
  // ],
  // lower: [
  //   {
  //     id: 389340,
  //     status: 'Finished',
  //     has_conflict: false,
  //     on_solution: false,
  //     round_id: 6084,
  //     order: 1,
  //     code: 'OCgwpWk',
  //     match_no: 5,
  //     start_at: null,
  //     is_losers_match: true,
  //     publisher_match_code: null,
  //     nextMatchId: 'Md1oHkm',
  //     winner_qualifies_to_position: 'away',
  //     nextLooserMatchId: null,
  //     loser_qualifies_to_position: null,
  //     home_qualified_from_status: 'winner',
  //     home_qualified_from_match_no: 3,
  //     away_qualified_from_status: 'loser',
  //     away_qualified_from_match_no: 4,
  //     participants: [
  //       {
  //         participant_id: 167384,
  //         participant_type: 'single',
  //         match_id: 389340,
  //         side: 'away',
  //         score: 1,
  //         is_winner: false,
  //         original: {
  //           id: 167384,
  //           country: 'Egypt',
  //           participant_name: 'youssef-maged-1161',
  //           reference_number: 'YM40885',
  //           slug: 'youssef-maged-1161',
  //           is_premium: false,
  //           avatar:
  //             'https://gbarena-development.s3.amazonaws.com/users/avatars/defaults/Egypt.user.png',
  //         },
  //       },
  //       {
  //         participant_id: 62955,
  //         participant_type: 'single',
  //         match_id: 389340,
  //         side: 'home',
  //         score: 2,
  //         is_winner: true,
  //         original: {
  //           id: 62955,
  //           country: 'Egypt',
  //           participant_name:
  //             'mahmoud',
  //           reference_number: 'KU83711',
  //           slug: 'ahmd-4',
  //           is_premium: false,
  //           avatar:
  //             'https://gbarena-development.s3.amazonaws.com/users/avatars/defaults/Egypt.user.png',
  //         },
  //       },
  //     ],
  //     claims: [],
  //   },
  //   {
  //     id: 389338,
  //     status: 'Finished',
  //     has_conflict: false,
  //     on_solution: false,
  //     round_id: 6083,
  //     order: 1,
  //     code: 'v98g9yX',
  //     match_no: 3,
  //     start_at: null,
  //     is_losers_match: true,
  //     publisher_match_code: null,
  //     nextMatchId: 'OCgwpWk',
  //     winner_qualifies_to_position: 'home',
  //     nextLooserMatchId: null,
  //     loser_qualifies_to_position: null,
  //     home_qualified_from_status: 'loser',
  //     home_qualified_from_match_no: 1,
  //     away_qualified_from_status: 'loser',
  //     away_qualified_from_match_no: 2,
  //     participants: [
  //       {
  //         participant_id: 62955,
  //         participant_type: 'single',
  //         match_id: 389338,
  //         side: 'home',
  //         score: 2,
  //         is_winner: true,
  //         original: {
  //           id: 62955,
  //           country: 'Egypt',
  //           participant_name:
  //             'mahmoud',
  //           reference_number: 'KU83711',
  //           slug: 'ahmd-4',
  //           is_premium: false,
  //           avatar:
  //             'https://gbarena-development.s3.amazonaws.com/users/avatars/defaults/Egypt.user.png',
  //         },
  //       },
  //       {
  //         participant_id: 122850,
  //         participant_type: 'single',
  //         match_id: 389338,
  //         side: 'away',
  //         score: 1,
  //         is_winner: false,
  //         original: {
  //           id: 122850,
  //           country: 'Kuwait',
  //           participant_name: 'Nawaf404',
  //           reference_number: 'NA65757',
  //           slug: 'nawaf404',
  //           is_premium: false,
  //           avatar:
  //             'https://gbarena-development.s3.amazonaws.com/users/avatars/defaults/default.png',
  //         },
  //       },
  //     ],
  //     claims: [],
  //   },
  // ],

  upper: [
    {
      "id":450021,
      "status":"To be played",
      "has_conflict":false,
      "on_solution":false,
      "round_id":6529,
      "order":1,
      "code":"bPsc0Dk",
      "match_no":1,
      "start_at":'2023-11-21T14:38:36Z',
      "publisher_match_code":null,
      "is_losers_match":false,
      "nextMatchId":"4QSMe5h",
      "winner_qualifies_to_position":"home",
      "nextLooserMatchId":"vAYhan1",
      "loser_qualifies_to_position":"home",
      "home_qualified_from_status":null,
      "home_qualified_from_match_no":null,
      "away_qualified_from_status":null,
      "away_qualified_from_match_no":null,
      "home":{
        "participant_id":103242,
        "participant_type":"single",
        "match_id":450021,
        "side":"home",
        "score":null,
        "is_winner":false,
        "tournament_participant":{
          "participant_id":103242,
          "type":"single",
          "participant_name":null,
          "is_dummy":false,
          "reference_number":null,
          "supported_required_inputs":null
        },
        "original":{
          "id":103242,
          "country":"Egypt",
          "participant_name":"VvCostavV",
          "reference_number":"VV80755",
          "slug":"vvcostavv",
          "is_premium":false,
          "avatar":"https:\/\/gbarena-development.s3.amazonaws.com\/users\/avatars\/defaults\/default.png"
        }
      },
      "away":{
        "participant_id":54315,
        "participant_type":"single",
        "match_id":450021,
        "side":"away",
        "score":null,
        "is_winner":false,
        "tournament_participant":{
          "participant_id":54315,
          "type":"single",
          "participant_name":null,
          "is_dummy":false,
          "reference_number":null,
          "supported_required_inputs":null
        },
        "original":{
          "id":54315,
          "country":"Egypt",
          "participant_name":"M7md_Ref3t",
          "reference_number":"M766912",
          "slug":"m7md-ref3t",
          "is_premium":false,
          "avatar":"https:\/\/gbarena-development.s3.amazonaws.com\/users\/avatars\/defaults\/default.png"
        }
      },
      "participants":[
        {
          "participant_id":103242,
          "participant_type":"single",
          "match_id":450021,
          "side":"home",
          "score":null,
          "is_winner":false,
          "original":{
            "id":103242,
            "country":"Egypt",
            "participant_name":"VvCostavV",
            "reference_number":"VV80755",
            "slug":"vvcostavv",
            "is_premium":false,
            "avatar":"https:\/\/gbarena-development.s3.amazonaws.com\/users\/avatars\/defaults\/default.png"
          }
        },
        {
          "participant_id":54315,
          "participant_type":"single",
          "match_id":450021,
          "side":"away",
          "score":null,
          "is_winner":false,
          "original":{
            "id":54315,
            "country":"Egypt",
            "participant_name":"M7md_Ref3t",
            "reference_number":"M766912",
            "slug":"m7md-ref3t",
            "is_premium":false,
            "avatar":"https:\/\/gbarena-development.s3.amazonaws.com\/users\/avatars\/defaults\/default.png"
          }
        }
      ],
      "claims":[

      ]
    },
    {
      "id":450022,
      "status":"To be played",
      "has_conflict":false,
      "on_solution":false,
      "round_id":6529,
      "order":2,
      "code":"jtgjlfa",
      "match_no":2,
      "start_at":null,
      "publisher_match_code":null,
      "is_losers_match":false,
      "nextMatchId":"4QSMe5h",
      "winner_qualifies_to_position":"away",
      "nextLooserMatchId":"vAYhan1",
      "loser_qualifies_to_position":"away",
      "home_qualified_from_status":null,
      "home_qualified_from_match_no":null,
      "away_qualified_from_status":null,
      "away_qualified_from_match_no":null,
      "home":{
        "participant_id":213464,
        "participant_type":"single",
        "match_id":450022,
        "side":"home",
        "score":null,
        "is_winner":false,
        "tournament_participant":{
          "participant_id":213464,
          "type":"single",
          "participant_name":null,
          "is_dummy":false,
          "reference_number":null,
          "supported_required_inputs":null
        },
        "original":{
          "id":213464,
          "country":"Egypt",
          "participant_name":"bydo-mhmd-4630",
          "reference_number":"BM82625",
          "slug":"bydo-mhmd-4630",
          "is_premium":false,
          "avatar":"https:\/\/gbarena-development.s3.amazonaws.com\/users\/avatars\/defaults\/Egypt.user.png"
        }
      },
      "away":{
        "participant_id":215318,
        "participant_type":"single",
        "match_id":450022,
        "side":"away",
        "score":null,
        "is_winner":false,
        "tournament_participant":{
          "participant_id":215318,
          "type":"single",
          "participant_name":null,
          "is_dummy":false,
          "reference_number":null,
          "supported_required_inputs":null
        },
        "original":{
          "id":215318,
          "country":"Palestine",
          "participant_name":"mostafa-abuamsha-2334",
          "reference_number":"MA77706",
          "slug":"mostafa-abuamsha-5060",
          "is_premium":false,
          "avatar":"https:\/\/gbarena-development.s3.amazonaws.com\/users\/avatars\/Avatar-google-2.1297903856342E%2B25.jpg"
        }
      },
      "participants":[
        {
          "participant_id":213464,
          "participant_type":"single",
          "match_id":450022,
          "side":"home",
          "score":null,
          "is_winner":false,
          "original":{
            "id":213464,
            "country":"Egypt",
            "participant_name":"bydo-mhmd-4630",
            "reference_number":"BM82625",
            "slug":"bydo-mhmd-4630",
            "is_premium":false,
            "avatar":"https:\/\/gbarena-development.s3.amazonaws.com\/users\/avatars\/defaults\/Egypt.user.png"
          }
        },
        {
          "participant_id":215318,
          "participant_type":"single",
          "match_id":450022,
          "side":"away",
          "score":null,
          "is_winner":false,
          "original":{
            "id":215318,
            "country":"Palestine",
            "participant_name":"mostafa-abuamsha-2334",
            "reference_number":"MA77706",
            "slug":"mostafa-abuamsha-5060",
            "is_premium":false,
            "avatar":"https:\/\/gbarena-development.s3.amazonaws.com\/users\/avatars\/Avatar-google-2.1297903856342E%2B25.jpg"
          }
        }
      ],
      "claims":[

      ]
    },
    {
      "id":450023,
      "status":"To be played",
      "has_conflict":false,
      "on_solution":false,
      "round_id":6529,
      "order":3,
      "code":"S22bZvw",
      "match_no":3,
      "start_at":null,
      "publisher_match_code":null,
      "is_losers_match":false,
      "nextMatchId":"4o5IxxS",
      "winner_qualifies_to_position":"home",
      "nextLooserMatchId":"aqrelXi",
      "loser_qualifies_to_position":"home",
      "home_qualified_from_status":null,
      "home_qualified_from_match_no":null,
      "away_qualified_from_status":null,
      "away_qualified_from_match_no":null,
      "home":{
        "participant_id":253346,
        "participant_type":"single",
        "match_id":450023,
        "side":"home",
        "score":null,
        "is_winner":false,
        "tournament_participant":{
          "participant_id":253346,
          "type":"single",
          "participant_name":null,
          "is_dummy":false,
          "reference_number":null,
          "supported_required_inputs":null
        },
        "original":{
          "id":253346,
          "country":"Lebanon",
          "participant_name":"saeed-marley-8192",
          "reference_number":"SM34559",
          "slug":"saeed-marley-8192",
          "is_premium":false,
          "avatar":"https:\/\/gbarena-development.s3.amazonaws.com\/users\/avatars\/Avatar-FKfUrvSnkoiBv7v.jpg"
        }
      },
      "away":{
        "participant_id":19378,
        "participant_type":"single",
        "match_id":450023,
        "side":"away",
        "score":null,
        "is_winner":false,
        "tournament_participant":{
          "participant_id":19378,
          "type":"single",
          "participant_name":null,
          "is_dummy":false,
          "reference_number":null,
          "supported_required_inputs":null
        },
        "original":{
          "id":19378,
          "country":"Egypt",
          "participant_name":"omar-muhammed",
          "reference_number":"OM78745",
          "slug":"omar-muhammed",
          "is_premium":false,
          "avatar":"https:\/\/gbarena-development.s3.amazonaws.com\/users\/avatars\/Avatar-F-1.9420277190186E%2B20.jpg"
        }
      },
      "participants":[
        {
          "participant_id":253346,
          "participant_type":"single",
          "match_id":450023,
          "side":"home",
          "score":null,
          "is_winner":false,
          "original":{
            "id":253346,
            "country":"Lebanon",
            "participant_name":"saeed-marley-8192",
            "reference_number":"SM34559",
            "slug":"saeed-marley-8192",
            "is_premium":false,
            "avatar":"https:\/\/gbarena-development.s3.amazonaws.com\/users\/avatars\/Avatar-FKfUrvSnkoiBv7v.jpg"
          }
        },
        {
          "participant_id":19378,
          "participant_type":"single",
          "match_id":450023,
          "side":"away",
          "score":null,
          "is_winner":false,
          "original":{
            "id":19378,
            "country":"Egypt",
            "participant_name":"omar-muhammed",
            "reference_number":"OM78745",
            "slug":"omar-muhammed",
            "is_premium":false,
            "avatar":"https:\/\/gbarena-development.s3.amazonaws.com\/users\/avatars\/Avatar-F-1.9420277190186E%2B20.jpg"
          }
        }
      ],
      "claims":[

      ]
    },
    {
      "id":450024,
      "status":"To be played",
      "has_conflict":false,
      "on_solution":false,
      "round_id":6529,
      "order":4,
      "code":"7hEPJrm",
      "match_no":4,
      "start_at":null,
      "publisher_match_code":null,
      "is_losers_match":false,
      "nextMatchId":"4o5IxxS",
      "winner_qualifies_to_position":"away",
      "nextLooserMatchId":"aqrelXi",
      "loser_qualifies_to_position":"away",
      "home_qualified_from_status":null,
      "home_qualified_from_match_no":null,
      "away_qualified_from_status":null,
      "away_qualified_from_match_no":null,
      "home":{
        "participant_id":248457,
        "participant_type":"single",
        "match_id":450024,
        "side":"home",
        "score":null,
        "is_winner":false,
        "tournament_participant":{
          "participant_id":248457,
          "type":"single",
          "participant_name":null,
          "is_dummy":false,
          "reference_number":null,
          "supported_required_inputs":null
        },
        "original":{
          "id":248457,
          "country":"Egypt",
          "participant_name":"mohamed-rabie-1278",
          "reference_number":"MR79255",
          "slug":"mohamed-rabie-1278",
          "is_premium":false,
          "avatar":"https:\/\/gbarena-development.s3.amazonaws.com\/users\/avatars\/Avatar-Vf6zjHdt8JBfF4x.jpg"
        }
      },
      "away":{
        "participant_id":212762,
        "participant_type":"single",
        "match_id":450024,
        "side":"away",
        "score":null,
        "is_winner":false,
        "tournament_participant":{
          "participant_id":212762,
          "type":"single",
          "participant_name":null,
          "is_dummy":false,
          "reference_number":null,
          "supported_required_inputs":null
        },
        "original":{
          "id":212762,
          "country":"Egypt",
          "participant_name":"ahmed-ehab-1919",
          "reference_number":"AE22704",
          "slug":"ahmed-ehab-6994",
          "is_premium":false,
          "avatar":"https:\/\/gbarena-development.s3.amazonaws.com\/users\/avatars\/Avatar-F-7.7710429513779E%2B20.jpg"
        }
      },
      "participants":[
        {
          "participant_id":248457,
          "participant_type":"single",
          "match_id":450024,
          "side":"home",
          "score":null,
          "is_winner":false,
          "original":{
            "id":248457,
            "country":"Egypt",
            "participant_name":"mohamed-rabie-1278",
            "reference_number":"MR79255",
            "slug":"mohamed-rabie-1278",
            "is_premium":false,
            "avatar":"https:\/\/gbarena-development.s3.amazonaws.com\/users\/avatars\/Avatar-Vf6zjHdt8JBfF4x.jpg"
          }
        },
        {
          "participant_id":212762,
          "participant_type":"single",
          "match_id":450024,
          "side":"away",
          "score":null,
          "is_winner":false,
          "original":{
            "id":212762,
            "country":"Egypt",
            "participant_name":"ahmed-ehab-1919",
            "reference_number":"AE22704",
            "slug":"ahmed-ehab-6994",
            "is_premium":false,
            "avatar":"https:\/\/gbarena-development.s3.amazonaws.com\/users\/avatars\/Avatar-F-7.7710429513779E%2B20.jpg"
          }
        }
      ],
      "claims":[

      ]
    },
    {
      "id":450027,
      "status":"To be played",
      "has_conflict":false,
      "on_solution":false,
      "round_id":6530,
      "order":1,
      "code":"4QSMe5h",
      "match_no":7,
      "start_at":null,
      "publisher_match_code":null,
      "is_losers_match":false,
      "nextMatchId":"ezKmZgy",
      "winner_qualifies_to_position":"home",
      "nextLooserMatchId":"EEwaFES",
      "loser_qualifies_to_position":"away",
      "home_qualified_from_status":"winner",
      "home_qualified_from_match_no":1,
      "away_qualified_from_status":"winner",
      "away_qualified_from_match_no":2,
      "home":null,
      "away":null,
      "participants":[

      ],
      "claims":[

      ]
    },
    {
      "id":450028,
      "status":"To be played",
      "has_conflict":false,
      "on_solution":false,
      "round_id":6530,
      "order":2,
      "code":"4o5IxxS",
      "match_no":8,
      "start_at":null,
      "publisher_match_code":null,
      "is_losers_match":false,
      "nextMatchId":"ezKmZgy",
      "winner_qualifies_to_position":"away",
      "nextLooserMatchId":"w7caY4d",
      "loser_qualifies_to_position":"away",
      "home_qualified_from_status":"winner",
      "home_qualified_from_match_no":3,
      "away_qualified_from_status":"winner",
      "away_qualified_from_match_no":4,
      "home":null,
      "away":null,
      "participants":[

      ],
      "claims":[

      ]
    },
    {
      "id":450031,
      "status":"To be played",
      "has_conflict":false,
      "on_solution":false,
      "round_id":6531,
      "order":1,
      "code":"ezKmZgy",
      "match_no":11,
      "start_at":null,
      "publisher_match_code":null,
      "is_losers_match":false,
      "nextMatchId":"1lTxElX",
      "winner_qualifies_to_position":"home",
      "nextLooserMatchId":"phxg3ks",
      "loser_qualifies_to_position":"away",
      "home_qualified_from_status":"winner",
      "home_qualified_from_match_no":7,
      "away_qualified_from_status":"winner",
      "away_qualified_from_match_no":8,
      "home":null,
      "away":null,
      "participants":[

      ],
      "claims":[

      ]
    },
    {
      "id":450033,
      "status":"To be played",
      "has_conflict":false,
      "on_solution":false,
      "round_id":6532,
      "order":1,
      "code":"1lTxElX",
      "match_no":13,
      "start_at":null,
      "publisher_match_code":null,
      "is_losers_match":false,
      "nextMatchId":null,
      "winner_qualifies_to_position":null,
      "nextLooserMatchId":null,
      "loser_qualifies_to_position":null,
      "home_qualified_from_status":"winner",
      "home_qualified_from_match_no":11,
      "away_qualified_from_status":"winner",
      "away_qualified_from_match_no":14,
      "home":null,
      "away":null,
      "participants":[

      ],
      "claims":[

      ]
    },
  ],
  lower: [
    {
      "id":450025,
      "status":"To be played",
      "has_conflict":false,
      "on_solution":false,
      "round_id":6529,
      "order":1,
      "code":"vAYhan1",
      "match_no":5,
      "start_at":null,
      "is_losers_match":true,
      "publisher_match_code":null,
      "nextMatchId":"w7caY4d",
      "winner_qualifies_to_position":"home",
      "nextLooserMatchId":null,
      "loser_qualifies_to_position":null,
      "home_qualified_from_status":"loser",
      "home_qualified_from_match_no":1,
      "away_qualified_from_status":"loser",
      "away_qualified_from_match_no":2,
      "home":null,
      "away":null,
      "participants":[

      ],
      "claims":[

      ]
    },
    {
      "id":450026,
      "status":"To be played",
      "has_conflict":false,
      "on_solution":false,
      "round_id":6529,
      "order":2,
      "code":"aqrelXi",
      "match_no":6,
      "start_at":null,
      "is_losers_match":true,
      "publisher_match_code":null,
      "nextMatchId":"EEwaFES",
      "winner_qualifies_to_position":"home",
      "nextLooserMatchId":null,
      "loser_qualifies_to_position":null,
      "home_qualified_from_status":"loser",
      "home_qualified_from_match_no":3,
      "away_qualified_from_status":"loser",
      "away_qualified_from_match_no":4,
      "home":null,
      "away":null,
      "participants":[

      ],
      "claims":[

      ]
    },
    {
      "id":450029,
      "status":"To be played",
      "has_conflict":false,
      "on_solution":false,
      "round_id":6530,
      "order":1,
      "code":"w7caY4d",
      "match_no":9,
      "start_at":null,
      "is_losers_match":true,
      "publisher_match_code":null,
      "nextMatchId":"4vlvhTl",
      "winner_qualifies_to_position":"home",
      "nextLooserMatchId":null,
      "loser_qualifies_to_position":null,
      "home_qualified_from_status":"winner",
      "home_qualified_from_match_no":5,
      "away_qualified_from_status":"loser",
      "away_qualified_from_match_no":8,
      "home":null,
      "away":null,
      "participants":[

      ],
      "claims":[

      ]
    },
    {
      "id":450030,
      "status":"To be played",
      "has_conflict":false,
      "on_solution":false,
      "round_id":6530,
      "order":2,
      "code":"EEwaFES",
      "match_no":10,
      "start_at":null,
      "is_losers_match":true,
      "publisher_match_code":null,
      "nextMatchId":"4vlvhTl",
      "winner_qualifies_to_position":"away",
      "nextLooserMatchId":null,
      "loser_qualifies_to_position":null,
      "home_qualified_from_status":"winner",
      "home_qualified_from_match_no":6,
      "away_qualified_from_status":"loser",
      "away_qualified_from_match_no":7,
      "home":null,
      "away":null,
      "participants":[

      ],
      "claims":[

      ]
    },
    {
      "id":450032,
      "status":"To be played",
      "has_conflict":false,
      "on_solution":false,
      "round_id":6531,
      "order":1,
      "code":"4vlvhTl",
      "match_no":12,
      "start_at":null,
      "is_losers_match":true,
      "publisher_match_code":null,
      "nextMatchId":"phxg3ks",
      "winner_qualifies_to_position":"home",
      "nextLooserMatchId":null,
      "loser_qualifies_to_position":null,
      "home_qualified_from_status":"winner",
      "home_qualified_from_match_no":9,
      "away_qualified_from_status":"winner",
      "away_qualified_from_match_no":10,
      "home":null,
      "away":null,
      "participants":[

      ],
      "claims":[

      ]
    },
    {
      "id":450034,
      "status":"To be played",
      "has_conflict":false,
      "on_solution":false,
      "round_id":6532,
      "order":1,
      "code":"phxg3ks",
      "match_no":14,
      "start_at":null,
      "is_losers_match":true,
      "publisher_match_code":null,
      "nextMatchId":"1lTxElX",
      "winner_qualifies_to_position":"away",
      "nextLooserMatchId":null,
      "loser_qualifies_to_position":null,
      "home_qualified_from_status":"winner",
      "home_qualified_from_match_no":12,
      "away_qualified_from_status":"loser",
      "away_qualified_from_match_no":11,
      "home":null,
      "away":null,
      "participants":[

      ],
      "claims":[

      ]
    }
  ],
};
